# Part 1.1-Generating and listening to sine waves

In [2]:
import numpy
import comp28512_utils as utils 
def playSin(F,Fs):
    A = 30000.0                 # amplitude of sine-wave
    T = 1.0 / Fs                # Sampling period (seconds)
    au_len = Fs * 3;
    n = numpy.arange(0, au_len) # Makes n a Numpy array of 0*T, 1*T, … 132300*T, 132300 = 44100*3
    y =  A * numpy.sin( 2 * numpy.pi * F * n * T )
    sin_audio = numpy.int16(y) 
    utils.Audio(sin_audio, rate=Fs,) 

In [3]:
print("F=220 Hz")
playSin(220,44100)
print("F=440 Hz")
playSin(440,44100)

F=220 Hz
Data written to /tmp/comp28512_GT2XzW.wav.


<source src="data:audio/wav;base64,UklGRrwJBABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YZgJBAAAAKwDVwcAC6cOShLo
FYEZFB2fICIknCcLK3AuyjEXNVY4hzuqPrxBvkSvR45KWk0SULdSRlXBVyVaclyoXsdgzWK6ZI5m
SGjnaW1r12wmbllvcHBrcUlyCnOvczZ0oXTudB11L3Ukdft0tXRRdNBzMnN3cqBxq3Cbb25uJW3B
a0JqqGj0ZiZlP2M/YSZf9VytWk5Y2VVOU65Q+k0yS1hIa0VtQl4/PzwROdU1izI0L9IrZCjtJGwh
4h1SGroWHRN7D9ULLAiBBNUAKv1++dT1LfKJ7urqUOe84y/gqtwu2bzVVNL4zqjLZsgxxQvC9b7v
u/q4F7ZHs4qw4a1Nq86oZKYSpNahs5+nnbSb2pkbmHWW6ZR5kySS65DNj8yO540fjXSM5ot1iyGL
64rSiteK+Yo5i5aLEIynjFyNLY4bjyWQS5GOkuuTZJX4lqaYbppQnEueXqCKos2kJqeXqRysuK5n
sSq0AbfpueO8778KwzXGbsm1zAjQaNPT1knayN1P4d7kdOgQ7LHvVvP/9qn6Vf4AAqwFVwn/DKMQ
RBTfF3UbAx+KIggmfSnnLEYwmDPeNhY6Pz1ZQGNDW0ZCSRdM2E6GUR9Uo1YRWWlbql3TX+Rh3WO8
ZYJnLmm/ajZskW3RbvRv/HDncbZyaHP8c3R0znQLdSt1LXURddh0gnQPdH5z0HIFch5xGnD6br5t
Z2z0amZpvmf8ZSBkKmIdYPdduVtkWflWeFTiUTdPeEymScJGy0PEQKw9hTpPNws0ujBdLfUpgSYF
I38f8RtdGMIUIhF+DdYJLAaBAtX+Kft/99bzMPCP7PLoW+XL4ULewtpL19/TfdAozd/JpMZ4w1rA
Tb1QumW3jLTGsRSvdqztqXqnHaXXoqmgkp6UnK+a45gxl5qVHZS8knaRS5A9j0yOdo2+jCOMpYtE
iwCL2orRiuaKGItoi9WLX4wGjcqNq46oj8KQ+JFJk7aUPZbfl5yZcpthnWqfiqHDoxKmeKj0qoat
LLDmsrS1lLiHu4q+nsHCxPXHNsuEzt7RRNW12DDcs98/49LmbOoK7q7xVfX++Kr8VQABBKwHVQv8
Dp4SPBbVGWYd8SBzJOwnWyu/LhcyYzWhONE78j4DQgRF80fQSppNUVDzUoFV+VdbWqdc2173YPpi
5WS3Zm9oDGqPa/ZsQ25zb4hwgHFcchtzvHNBdKl083QgdS91IXX2dK10R3TDcyNzZXKLcZRwgG9R
bgZtoGseaoJoy2b7ZBFjD2H0XsFcdloVWJ5VElNwULpN8UoUSCZFJkIWP/Y7xjiJNT4y5i6DKxQo
nCQaIZAd/hlmFskSJg+AC9cHLASAANT8Kfl/9djxNe6W6vzmaePc31jc3dhs1QXSqs5cyxrI58TD
wa6+qru2uNW1B7NLsKStEquVqC2m3aOkoYKfeZ2Im7GZ85dQlseUWZMGktCQtY+2jtSNDo1mjNqL
bIsbi+iK0YrZiv6KQIugixyMtoxtjUGOMo8/kGiRrJINlIiVHpfPmJmafZx6npCgvaICpV6n0KlY
rPWuprFrtEO3LroqvTbAU8N/xrnJAc1W0LfTI9ea2hneouEx5cjoZewG8KvzVPf/+qv+VgICBqwJ
VA34EJgUMxjIG1Yf3CJZJs0pNi2TMOUzKTdgOog9oECoQ6BGhUlYTBhPw1FbVN1WSVmeW91dBGAT
Yglk5mWqZ1Np4mpWbK9t7G4OcBNx+3HHcnZzCXR9dNV0D3UsdSt1DXXSdHl0A3Rvc79y8XEHcQFw
3m6gbUZs0WpBaZZn0WXzY/xh7F/EXYRbLVnAVj1UpVH4TjdMZEl9RoVDfUBjPTs6BDe/M20wDi2l
KTEmsyItH54bCRhuFM4QKQ2BCdcFKwKA/tT6KfeB89zvOuye6AjleOHw3XHa+9aQ0y/Q28yUyVrG
LsMSwAe9C7oit0u0h7HWrjqss6lCp+eko6J3oGKeZ5yEmrqYC5d2lfyTnZJZkTKQJo83jmWNr4wW
jJuLPIv7itiK0orpih6LcIvgi22MF43djcGOwY/dkBWSaZPYlGKWB5jGmZ6bkJ2an72h96NJprGo
L6vDrWuwJ7P2tdi4zLvRvufBDMVAyILL0c4t0pTVBtmB3AbgkuMm58DqX+4D8qr1VPn//KoAVwQC
CKsLUQ/zEpAWKBq5HUMhxCQ8KKorDS9kMq817DgaPDo/SkJJRTZIEkvaTY9QMFO7VTJYklrbXA1f
J2EoYxFl4GaVaDBqsWsWbV9ujW+fcJVxbnIqc8pzTHSxdPl0I3UvdR918HSldDx0tnMSc1JydXF8
cGZvNG7nbH5r+mlbaKJm0GTkYt9gwV6MXEBa3VdkVdVSMlB6Ta9K0UfhROBBzj6sO3w4PTXwMZgu
MyvEJ0okyCA9HasZEhZ0EtEOKwuCB9YDKgB//NT4KvWD8eDtQuqp5hbjit8H3I3YHNW30V3OD8vP
x53EesFnvmS7c7iTtcayDbBnrdeqXKj3paijcaFSn0qdXJuHmcyXK5aklDmT6ZG1kJyPoI7Bjf6M
WIzPi2OLFYvkitGK24oCi0eLqospjMaMgI1WjkmPWJCEkcuSLpSslUSX95jEmqqcqp7BoPGiOKWW
pwqqlKwzr+axrbSHt3K6cL1+wJzDysYFyk/NpdAG1HPX69pr3vThheUc6bnsW/AA9Kn3VPsA/6sC
VwYBCqgNTBHsFIcYGxyoHy0jqiYcKoUt4TAyNHU3qjrRPedA7kPkRsdJmUxWTwBSllQWV4BZ1FsQ
XjVgQmI2ZBFm0md5aQVrd2zNbQhvJnApcQ9y2HKFcxR0h3TcdBN1LXUqdQl1y3RvdPZzYHOtct1x
8XDob8Nugm0lbK1qG2luZ6dlxmPNYbpfkF1OW/VYhlYBVGdRuU72SyFJOUZAQzVAGz3xObg2cjMf
ML8sVSngJWEi2h5LG7YXGhR5ENQMLAmBBdYBKv5/+tT2LPOH7+brSui15Cbhn90g2qvWQdPhz47M
SMkPxuXCy7/AvMe537YKtEexma7/q3qpC6eypHCiRqAznjqcWZqSmOWWU5Xbk36SPZEYkA+PI45T
jaCMCoyRizWL94rWitOK7Yoki3mL7It7jCiN8Y3XjtqP+JAzkomT+5SHli6Y75nKm76dy5/woSyk
gKbqqGqrAK6qsGezObYcuRK8Gb8vwlbFi8jOyx/Pe9Lk1VbZ09xY4OXjeecU67TuWPL/9an5Vf0A
AawEVwgADKUPRxPkFnsaDB6VIRUljSj6K1svsTL7NTY5ZDyCP5BCjkV5SFNLGk7NUGxT9lVqWMha
D10/X1ZhVmM8ZQlnvGhUatJrNW18bqhvt3CqcYByOnPXc1Z0uXT+dCV1L3Ucdet0nXQxdKhzAnM/
cmBxZHBLbxdux2xca9VpNGh5ZqRktmKuYI9eWFwJWqRXKVWZUvNPOk1tSo1HnESZQYY+YzsxOPE0
ozFJLuQqcyf5I3Yg6hxXGb4VIBJ9DtYKLAeBA9b/Kvx++NX0L/GM7e7pVebD4jjftts82M3UaNEQ
zsPKhMdUxDLBIL4fuy+4UbWGss6vK62cqiOowKV0oz+hIZ8cnTCbXpmllwaWgpQZk8yRmpCEj4uO
ro3ujEqMxItbixCL4YrRit2KB4tPi7SLNozWjJKNa45hj3OQoZHqkk+U0JVrlyCZ75rYnNme86Al
o26lzqdFqtCsca8msu60yre3ura9xsDmwxTHUcqczfPQVtTE1zzbvd5H4tjlcOkN7a/wVfT+96n7
Vv8BA6wGVgr9DaERQBXaGG4c+h9/I/ombCrTLS8xfjTAN/Q6GT4vQTREKEcKStlMlU89UtFUT1e3
WQlcQ15mYHBiYmQ6Zvlnnmkoa5ds620jbz9wP3

F=440 Hz
Data written to /tmp/comp28512_o68FEY.wav.


<source src="data:audio/wav;base64,UklGRrwJBABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YZgJBAAAAFcHpw7oFRQdIiQL
K8oxVjiqPr5EjkoSUEZVJVqoXs1ijmbnaddsWW9rcQpzNnTudC91+3RRdDJzoHGbbyVtQmr0Zj9j
Jl+tWtlVrlAyS2tFXj8ROYsy0ivtJOIduhZ7DywI1QB++S3y6uq846rcvNX4zmbIC8Lvuxe2irBN
q2Sm1qGnndqZdZZ5k+uQzI4fjeaLIYvSivmKlounjC2OJZCOkmSVpphQnF6gzaSXqbiuKrTpue+/
Nca1zGjTSdpP4XTose//9lX+rAX/DEQUdRuKIn0pRjDeNj89Y0NCSdhOH1QRWapd5GG8ZS5pNmzR
bvxwtnL8c850K3URdYJ0fnMFchpwvm30ar5nIGQdYLlb+VbiUXhMwkbEQIU6CzRdLYEmfx9dGCIR
1gmBAin71vOP7FvlQt5L133Q38l4w029ZbfGsXaseqfXopKer5oxlx2UdpE9j3aNI4xEi9qK5opo
i1+Myo2oj/iRtpTfl3Kbap/Do3iohq3mspS4ir7CxDbL3tG12LPf0uYK7lX1qvwBBFULnhLVGfEg
7Ce/LmM10TsDQvNHmk3zUvlXp1z3YOVkb2iPa0NuiHBccrxzqXQgdSF1rXTDc2VylHBRbqBrgmj7
ZA9hwVwVWBJTuk0USCZC9juJNeYuFCgaIf4ZyRKACywE1Px/9TXu/Obc393YBdJcy+fErr62uAez
pK2VqN2jgp+Im/OXx5QGkrWP1I1mjGyL6IrZikCLHIxtjTKPaJENlB6XmZp6nr2iXqdYrKaxQ7cq
vVPDuclW0CPXGd4x5WXsq/P/+lYCrAn4EDMYVh9ZJjYt5TNgOqBAoEZYTMNR3VaeWwRgCWSqZ+Jq
r20OcPtxdnN9dA91K3XSdAN0v3IHcd5uRmxBadFl/GHEXS1ZPVT4TmRJhUNjPQQ3bTClKbMinhtu
FCkN1wWA/in33O+e6HjhcdqQ09vMWsYSwAu6S7TWrrOp56R3oGecuph2lZ2SMpA3jq+Mm4v7itKK
HovgixeNwY7dkGmTYpbGmZCdvaFJpi+ra7D2tcy758FAyNHOlNWB3JLjwOoD8lT5qgACCFEPkBa5
HcQkqitkMuw4Oj9JRRJLj1C7VZJaDV8oY+BmMGoWbY1vlXEqc0x0+XQvdfB0PHQSc3VxZm/nbPpp
ombkYsFeQFpkVTJQr0rhRM4+fDjwMTMrSiQ9HRIW0Q6CByoA1PiD8ULqFuMH3BzVXc7Px3rBZLuT
tQ2w16r3pXGhSp2HmSuWOZO1kKCO/ozPixWL0YoCi6qLxoxWjliQy5KslfeYqpzBoDilCqozr620
crp+wMrGT80G1Ova9OEc6VvwqfcA/1cGqA3sFBscLSMcKuEwdTfRPe5Dx0lWT5ZUgFkQXkJiEWZ5
aXdsCG8pcdhyFHTcdC11CXVvdGBz3XHob4JtrWpuZ8Zjul9OW4ZWZ1H2SzlGNUDxOXIzvyzgJdoe
thd5ECwJ1gF/+izz5uu15J/dq9bhz0jJ5cLAvN+2R7H/qwuncKIznlma5Zbbkz2RD49TjQqMNYvW
iu2KeYt7jPGN2o8zkvuULpjKm8ufLKTqqACuZ7McuRm/VsXOy3vSVtlY4HnntO7/9VX9rAQADEcT
exqVIY0oWy/7NWQ8kEJ5SBpObFNqWA9dVmE8Zbxo0mt8brdwgHLXc7l0JXUcdZ10qHM/cmRwF25c
azRopGSuYFhcpFeZUjpNjUeZQWM78TRJLnMndiBXGSAS1gqBAyr81fSM7VXmON882GjRw8pUxCC+
L7iGsiutI6h0oyGfMJull4KUzJGEj66NSoxbi+GK3YpPizaMko1hj6GRT5Rrl++a2Z4lo86n0Kwm
ssq3tr3mw1HK89DE173e2OUN7VX0qfsBA1YKoRHaGPof+ibTLX409DovQShH2Uw9Uk9XCVxmYGJk
+Wcoa+ttP3AjcpNzkHQXdSh1xHTqc5ty2nCnbgRs9Wh8ZZ5hXV2+WMZTeU7eSPlC0jxsNtEvBSkQ
IvgaxhN/DCwF1f1/9jLv9+fT4M/Z8tJBzMXFg7+DucmzW65AqXykFKANnGqYL5Vgkv+PD46RjIeL
84rUiiuL94s5je2OFJGqk62WGprtnSOit6alq+iwe7ZYvHjC18htzzPWJN045GjrrPL++VUBrAj6
DzgXXh5mJUks/zKBOco/0kWVSwtRMFb+WnBfg2MxZ3hqVG3Bb79xSnNgdAJ1L3XldCZ08nJKcTBv
p2ywaU9mh2JcXtNZ7lS1TytKVkQ9PuY3VjGUKqgjlxxqFSgO1waA/yn42vCa6XDiZNt91MLNOsfq
wNq6D7WQr2KqiqUMoe+cNZnilfqSgJB1jt2MuYsKi9GKDYu/i+WMgI6NkAqT9JVJmQadJaGlpX+q
r68wtfy6DsFfx+nNpdSN25rixOkE8VT4q/8CB1IOlBXBHNAjvCp8MQs4Yj55RExK1E8MVe5Zdl6f
YmRmw2m3bD5vVXH6cit06HQvdQB1W3RCc7RxtW9EbWZqHWdsY1df41oTVuxQdEuwRaY/XDnYMiEs
PiU1Hg4X0A+BCCsB1PmC8j7rD+T73AvWRs+xyFTCNbxatsmwiKucpgmi1p0EmpqWmZMGkeKOMI3x
iyiL04r1ioyLmIwZjgyQb5JBlX6YI5wtoJekXal6rumzpbmnv+rFaMwZ0/jZ/eAh6F3vqfYA/lcF
qgzwEyIbOCItKfgvkjb2PB1D/0iZTuRT2lh2XbVhkmUIaRVstW7lcKRy8HPHdCl1FXWLdIxzGXIz
cNxtF2vlZ0xkTWDuWzJXH1K5TAZHC0HPOlg0rC3SJtEfsBh3ESwK1gJ/+yv04+yu5ZTenNfM0CvK
wcOTvai3BrKyrLKnC6PBntqaWJc/lJKRVY+JjTCMS4vciuOKX4tRjLeNkI/akZOUuJdGmzmfjqM/
qEmtprJRuES+ecTpypDRZNhh33/mtu0A9VT8rAMAC0oSgRmfIJwncC4XNYc7vEGvR1pNt1LBV3Jc
x2C6ZEhobWsmbnBwSXKvc6F0HXUkdbV00HN3cqtwbm7Ba6hoJmU/YfVcTlhOU/pNWEhtQj881TU0
L2QobCFSGh0T1QuBBCr91PWJ7lDnL+Au2VTSqMsxxfW++rhHs+GtzqgSpLOftJsbmOmUJJLNj+eN
dIx1i+uK14o5ixCMXI0bj0uR65P4lm6aS56KoianHKxnsQG347wKw27JCNDT1sjd3uQQ7FbzqfoA
AlcJoxDfFwMfCCbnLJgzFjpZQFtGF0yGUaNWaVvTX91jgme/apFt9G/ncWhzdHQLdS112HQPdNBy
HnH6bmdsZmn8ZSpi911kWXhUN0+mSctDrD1PN7ow9SkFI/EbwhR+DSwG1f5/9zDw8ujL4cLa39Mo
zaTGWsBQuoy0FK/tqR2lqaCUnOOYmpW8kkuQTI6+jKWLAIvRihiL1YsGjauOwpBJkz2WnJlhnYqh
Eqb0qiywtLWHu57B9ceEzkTVMNw/42zqrvH++FUArAf8DjwWZh1zJFsrFzKhOPI+BEXQSlFQgVVb
Wtte+mK3Zgxq9mxzb4BxG3NBdPN0L3X2dEd0I3OLcYBvBm0eastmEWP0XnZanlVwUPFKJkUWP8Y4
PjKDK5wkkB1mFiYP1weAACn52PGW6mnjWNxs1arOGsjDwaq71bVLsBKrLaakoXmdsZlQllmT0JC2
jg6N2osbi9GK/oqgi7aMQY4/kKySiJXPmH2ckKACpdCp9a5rtC66NsB/xgHNt9Oa2qLhyOgG8FT3
q/4CBlQNmBTIG9wizSmTMCk3iD2oQ4VJGE9bVElZ3V0TYuZlU2lWbOxuE3HHcgl01XQsdQ11eXRv
c/FxAXCgbdFqlmfzY+xfhFvAVqVRN0x9Rn1AOz

In [4]:
print("F=1000 Hz")
playSin(1000,44100)
print("F=2000 Hz")
playSin(2000,44100)
print("F=4000 Hz")
playSin(4000,44100)
print("F=8000 Hz")
playSin(8000,44100)
print("F=16000 Hz")
playSin(16000,44100)
print("F=18000 Hz")
playSin(18000,44100)
print("F=20000 Hz")
playSin(20000,44100)

F=1000 Hz
Data written to /tmp/comp28512_c2AZtm.wav.


<source src="data:audio/wav;base64,UklGRrwJBABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YZgJBAAAAKMQ8SCTMDo/mUxq
WHBieGpYcPBzL3UPdJRw0WrkYvVYOk3uP1YxviF3EdUAMPDc3y/QesEKtCOoBJ7ileaPMIzSitWL
Mo/YlKqcgKYmsmC/6c123bbtVf78DlYfDS/RPVNLT1eGYcNp22+vcyt1R3QHcX5rxmMJWnlOUkHY
MlYjHROBAtjxeOG30eXCUbVAqfGempZlkHSM2oqgi8GOLpTKm26l6LD9vWjM3tsQ7Kr8VA25HYUt
ZDwKSjBWlmAIaVlvaHMgdXl0dXElbKRkGVu1T7NCWDTtJMIULASB8xbjQdNUxJy2Yqrjn1iX65C+
jOiKcItWjomT75pipK+vnbzpyknabOr/+qsLGxz6K/Q6vUgMVaJfSGjRbhtzD3WldN1xx2x8ZSNc
7FARRNU1gSZmFtcFKvW15M3UxcXst4ir2qAbmHaRDo37ikeL8Y3qkhqaWaN6rkK7bsm12MjoVPkB
CnsabCqBOWxH5FOoXoJnQ27Hcvl0y3Q/cmNtT2YpXR9Sa0VPNxQoCRiCB9T2VeZb1jrHPrmyrNah
45gGkmWNFYski5KNUZJJmVaiSa3pufXHI9cm56n3VwjaGN0oCzgXRrdSql23Zq9tbnLcdOt0m3L6
bR1nKl5OU8JGxjilKasZLAl++Pfn7NexyJW64a3XorGZnZLBjTWLB4s5jb2RfphYoRyslLh/xpTV
heX/9awGOBdLJ5I2vkSGUadc5mUWbQ9yuXQFdfJyim7lZyZfeFQUSDs6MytLG9YKKfqa6X/ZK8rv
uxSv3aOEmjmTI45bi/GK5YwvkbiXXqD0qkO3DMUG1OXjVfQBBZQVtyUXNWNDUVCeWxFld2yqcZB0
GHVCcxVvqGgdYJ5VZEmsO78s6hx/DNT7PusT26jLTb1LsOekXJvbk4uOh4vgipiMp5D4lmqf0Kn2
tZzDe9JH4qzyVgPwEyIkmDMDQhhPklo2ZNJrP3FgdCZ1jHObb2ZpD2HAVq9KGz1JLogeKA5//ePs
qtwoza6+h7H3pTqcgpT5jrmL1YpRjCWQPZZ6nrGorbQvwvPQquAE8asBShKKIhcyoEDaTYBZVmMo
a85wK3QuddBzGnAeavxh3Vf2S4Y+0S8kINAPK/+J7kLeqs4SwMayC6ccnS+VbI/xi9GKEIyoj4iV
kJ2Wp2ezxsBtzw/fXe8AAKMQ8SCTMDo/mUxqWHBieGpYcPBzL3UPdJRw0WrkYvVYOk3uP1YxviF3
EdUAMPDc3y/QesEKtCOoBJ7ileaPMIzSitWLMo/YlKqcgKYmsmC/6c123bbtVf78DlYfDS/RPVNL
T1eGYcNp22+vcyt1R3QHcX5rxmMJWnlOUkHYMlYjHROBAtjxeOG30eXCUbVAqfGempZlkHSM2oqg
i8GOLpTKm26l6LD9vWjM3tsQ7Kr8VA25HYUtZDwKSjBWlmAIaVlvaHMgdXl0dXElbKRkGVu1T7NC
WDTtJMIULASB8xbjQdNUxJy2Yqrjn1iX65C+jOiKcItWjomT75pipK+vnbzpyknabOr/+qsLGxz6
K/Q6vUgMVaJfSGjRbhtzD3WldN1xx2x8ZSNc7FARRNU1gSZmFtcFKvW15M3UxcXst4ir2qAbmHaR
Do37ikeL8Y3qkhqaWaN6rkK7bsm12MjoVPkBCnsabCqBOWxH5FOoXoJnQ27Hcvl0y3Q/cmNtT2Yp
XR9Sa0VPNxQoCRiCB9T2VeZb1jrHPrmyrNah45gGkmWNFYski5KNUZJJmVaiSa3pufXHI9cm56n3
VwjaGN0oCzgXRrdSql23Zq9tbnLcdOt0m3L6bR1nKl5OU8JGxjilKasZLAl++Pfn7NexyJW64a3X
orGZnZLBjTWLB4s5jb2RfphYoRyslLh/xpTVheX/9awGOBdLJ5I2vkSGUadc5mUWbQ9yuXQFdfJy
im7lZyZfeFQUSDs6MytLG9YKKfqa6X/ZK8rvuxSv3aOEmjmTI45bi/GK5YwvkbiXXqD0qkO3DMUG
1OXjVfQBBZQVtyUXNWNDUVCeWxFld2yqcZB0GHVCcxVvqGgdYJ5VZEmsO78s6hx/DNT7PusT26jL
Tb1LsOekXJvbk4uOh4vgipiMp5D4lmqf0Kn2tZzDe9JH4qzyVgPwEyIkmDMDQhhPklo2ZNJrP3Fg
dCZ1jHObb2ZpD2HAVq9KGz1JLogeKA5//ePsqtwoza6+h7H3pTqcgpT5jrmL1YpRjCWQPZZ6nrGo
rbQvwvPQquAE8asBShKKIhcyoEDaTYBZVmMoa85wK3QuddBzGnAeavxh3Vf2S4Y+0S8kINAPK/+J
7kLeqs4SwMayC6ccnS+VbI/xi9GKEIyoj4iVkJ2Wp2ezxsBtzw/fXe8AAKMQ8SCTMDo/mUxqWHBi
eGpYcPBzL3UPdJRw0WrkYvVYOk3uP1YxviF3EdUAMPDc3y/QesEKtCOoBJ7ileaPMIzSitWLMo/Y
lKqcgKYmsmC/6c123bbtVf78DlYfDS/RPVNLT1eGYcNp22+vcyt1R3QHcX5rxmMJWnlOUkHYMlYj
HROBAtjxeOG30eXCUbVAqfGempZlkHSM2oqgi8GOLpTKm26l6LD9vWjM3tsQ7Kr8VA25HYUtZDwK
SjBWlmAIaVlvaHMgdXl0dXElbKRkGVu1T7NCWDTtJMIULASB8xbjQdNUxJy2Yqrjn1iX65C+jOiK
cItWjomT75pipK+vnbzpyknabOr/+qsLGxz6K/Q6vUgMVaJfSGjRbhtzD3WldN1xx2x8ZSNc7FAR
RNU1gSZmFtcFKvW15M3UxcXst4ir2qAbmHaRDo37ikeL8Y3qkhqaWaN6rkK7bsm12MjoVPkBCnsa
bCqBOWxH5FOoXoJnQ27Hcvl0y3Q/cmNtT2YpXR9Sa0VPNxQoCRiCB9T2VeZb1jrHPrmyrNah45gG
kmWNFYski5KNUZJJmVaiSa3pufXHI9cm56n3VwjaGN0oCzgXRrdSql23Zq9tbnLcdOt0m3L6bR1n
Kl5OU8JGxjilKasZLAl++Pfn7NexyJW64a3XorGZnZLBjTWLB4s5jb2RfphYoRyslLh/xpTVheX/
9awGOBdLJ5I2vkSGUadc5mUWbQ9yuXQFdfJyim7lZyZfeFQUSDs6MytLG9YKKfqa6X/ZK8rvuxSv
3aOEmjmTI45bi/GK5YwvkbiXXqD0qkO3DMUG1OXjVfQBBZQVtyUXNWNDUVCeWxFld2yqcZB0GHVC
cxVvqGgdYJ5VZEmsO78s6hx/DNT7PusT26jLTb1LsOekXJvbk4uOh4vgipiMp5D4lmqf0Kn2tZzD
e9JH4qzyVgPwEyIkmDMDQhhPklo2ZNJrP3FgdCZ1jHObb2ZpD2HAVq9KGz1JLogeKA5//ePsqtwo
za6+h7H3pTqcgpT5jrmL1YpRjCWQPZZ6nrGorbQvwvPQquAE8asBShKKIhcyoEDaTYBZVmMoa85w
K3QuddBzGnAeavxh3Vf2S4Y+0S8kINAPK/+J7kLeqs4SwMayC6ccnS+VbI/xi9GKEIyoj4iVkJ2W
p2ezxsBtzw/fXe8AAKMQ8SCTMDo/mUxqWHBieGpYcPBzL3UPdJRw0WrkYvVYOk3uP1YxviF3EdUA
MPDc3y/QesEKtCOoBJ7ileaPMIzSitWLMo/YlKqcgKYmsmC/6c123bbtVf78DlYfDS/RPVNLT1eG
YcNp22+vcyt1R3QHcX5rxmMJWnlOUkHYMlYjHROBAtjxeOG30eXCUbVAqfGempZlkHSM2oqgi8GO
LpTKm26l6LD9vWjM3tsQ7Kr8VA25HYUtZDwKSjBWlmAIaVlvaHMgdXl0dXElbKRkGVu1T7NCWDTt
JMIULASB8xbjQdNUxJy2Yqrjn1iX65C+jOiKcI

F=2000 Hz
Data written to /tmp/comp28512_NcCD5G.wav.


<source src="data:audio/wav;base64,UklGRrwJBABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YZgJBAAAAPEgOj9qWHhq8HMP
dNFq9VjuP74h1QDc33rBI6jilTCM1YvYlICmYL923VX+Vh/RPU9Xw2mvc0d0fmsJWlJBViOBAnjh
5cJAqZqWdIygiy6UbqX9vd7bqvy5HWQ8MFYIaWhzeXQlbBlbs0LtJCwEFuNUxGKqWJe+jHCLiZNi
pJ28Sdr/+hsc9DoMVUhoG3OldMdsI1wRRIEm1wW15MXFiKsbmA6NR4vqklmjQru12FT5exqBOeRT
gmfHcst0Y20pXWtFFCiCB1XmOseyrOOYZY0ki1GSVqLpuSPXqffaGAs4t1K3Zm5y63T6bSpewkal
KSwJ9+exyOGtsZnBjQeLvZFYoZS4lNX/9TgXkjaGUeZlD3IFdYpuJl8USDMr1gqa6SvKFK+EmiOO
8YovkV6gQ7cG1FX0lBUXNVFQEWWqcRh1FW8dYGRJvyx/DD7rqMtLsFybi47giqeQap/2tXvSrPLw
E5gzGE82ZD9xJnWbbw9hr0pJLigO4+wozYexOpz5jtWKJZB6nq2089AE8UoSFzLaTVZjznAudRpw
/GH2S9Ev0A+J7qrOxrIcnWyP0Yqoj5CdZ7Ntz13voxCTMJlMcGJYcC91lHDkYjpNVjF3ETDwL9AK
tASe5o/SijKPqpwmsunNtu38Dg0vU0uGYdtvK3UHccZjeU7YMh0T2PG30VG18Z5lkNqKwY7Km+iw
aMwQ7FQNhS0KSpZgWW8gdXVxpGS1T1g0whSB80HTnLbjn+uQ6IpWju+ar6/pymzqqwv6K71Iol/R
bg913XF8ZexQ1TVmFir1zdTst9qgdpH7ivGNGpp6rm7JyOgBCmwqbEeoXkNu+XQ/ck9mH1JPNwkY
1PZb1j651qEGkhWLko1JmUmt9ccm51cI3SgXRqpdr23cdJtyHWdOU8Y4qxl++OzXlbrXop2SNYs5
jX6YHKx/xoXlrAZLJ75Ep1wWbbl08nLlZ3hUOzpLGyn6f9nvu92jOZNbi+WMuJf0qgzF5eMBBbcl
Y0OeW3dskHRCc6honlWsO+oc1PsT202956Tbk4eLmIz4ltCpnMNH4lYDIiQDQpJa0mtgdIxzZmnA
Vhs9iB5//arcrr73pYKUuYtRjD2WsagvwqrgqwGKIqBAgFkoayt00HMeat1Xhj4kICv/Qt4SwAun
L5XxixCMiJWWp8bAD98AAPEgOj9qWHhq8HMPdNFq9VjuP74h1QDc33rBI6jilTCM1YvYlICmYL92
3VX+Vh/RPU9Xw2mvc0d0fmsJWlJBViOBAnjh5cJAqZqWdIygiy6UbqX9vd7bqvy5HWQ8MFYIaWhz
eXQlbBlbs0LtJCwEFuNUxGKqWJe+jHCLiZNipJ28Sdr/+hsc9DoMVUhoG3OldMdsI1wRRIEm1wW1
5MXFiKsbmA6NR4vqklmjQru12FT5exqBOeRTgmfHcst0Y20pXWtFFCiCB1XmOseyrOOYZY0ki1GS
VqLpuSPXqffaGAs4t1K3Zm5y63T6bSpewkalKSwJ9+exyOGtsZnBjQeLvZFYoZS4lNX/9TgXkjaG
UeZlD3IFdYpuJl8USDMr1gqa6SvKFK+EmiOO8YovkV6gQ7cG1FX0lBUXNVFQEWWqcRh1FW8dYGRJ
vyx/DD7rqMtLsFybi47giqeQap/2tXvSrPLwE5gzGE82ZD9xJnWbbw9hr0pJLigO4+wozYexOpz5
jtWKJZB6nq2089AE8UoSFzLaTVZjznAudRpw/GH2S9Ev0A+J7qrOxrIcnWyP0Yqoj5CdZ7Ntz13v
oxCTMJlMcGJYcC91lHDkYjpNVjF3ETDwL9AKtASe5o/SijKPqpwmsunNtu38Dg0vU0uGYdtvK3UH
ccZjeU7YMh0T2PG30VG18Z5lkNqKwY7Km+iwaMwQ7FQNhS0KSpZgWW8gdXVxpGS1T1g0whSB80HT
nLbjn+uQ6IpWju+ar6/pymzqqwv6K71Iol/Rbg913XF8ZexQ1TVmFir1zdTst9qgdpH7ivGNGpp6
rm7JyOgBCmwqbEeoXkNu+XQ/ck9mH1JPNwkY1PZb1j651qEGkhWLko1JmUmt9ccm51cI3SgXRqpd
r23cdJtyHWdOU8Y4qxl++OzXlbrXop2SNYs5jX6YHKx/xoXlrAZLJ75Ep1wWbbl08nLlZ3hUOzpL
Gyn6f9nvu92jOZNbi+WMuJf0qgzF5eMBBbclY0OeW3dskHRCc6honlWsO+oc1PsT202956Tbk4eL
mIz4ltCpnMNH4lYDIiQDQpJa0mtgdIxzZmnAVhs9iB5//arcrr73pYKUuYtRjD2WsagvwqrgqwGK
IqBAgFkoayt00HMeat1Xhj4kICv/Qt4SwAunL5XxixCMiJWWp8bAD98AAPEgOj9qWHhq8HMPdNFq
9VjuP74h1QDc33rBI6jilTCM1YvYlICmYL923VX+Vh/RPU9Xw2mvc0d0fmsJWlJBViOBAnjh5cJA
qZqWdIygiy6UbqX9vd7bqvy5HWQ8MFYIaWhzeXQlbBlbs0LtJCwEFuNUxGKqWJe+jHCLiZNipJ28
Sdr/+hsc9DoMVUhoG3OldMdsI1wRRIEm1wW15MXFiKsbmA6NR4vqklmjQru12FT5exqBOeRTgmfH
cst0Y20pXWtFFCiCB1XmOseyrOOYZY0ki1GSVqLpuSPXqffaGAs4t1K3Zm5y63T6bSpewkalKSwJ
9+exyOGtsZnBjQeLvZFYoZS4lNX/9TgXkjaGUeZlD3IFdYpuJl8USDMr1gqa6SvKFK+EmiOO8Yov
kV6gQ7cG1FX0lBUXNVFQEWWqcRh1FW8dYGRJvyx/DD7rqMtLsFybi47giqeQap/2tXvSrPLwE5gz
GE82ZD9xJnWbbw9hr0pJLigO4+wozYexOpz5jtWKJZB6nq2089AE8UoSFzLaTVZjznAudRpw/GH2
S9Ev0A+J7qrOxrIcnWyP0Yqoj5CdZ7Ntz13voxCTMJlMcGJYcC91lHDkYjpNVjF3ETDwL9AKtASe
5o/SijKPqpwmsunNtu38Dg0vU0uGYdtvK3UHccZjeU7YMh0T2PG30VG18Z5lkNqKwY7Km+iwaMwQ
7FQNhS0KSpZgWW8gdXVxpGS1T1g0whSB80HTnLbjn+uQ6IpWju+ar6/pymzqqwv6K71Iol/Rbg91
3XF8ZexQ1TVmFir1zdTst9qgdpH7ivGNGpp6rm7JyOgBCmwqbEeoXkNu+XQ/ck9mH1JPNwkY1PZb
1j651qEGkhWLko1JmUmt9ccm51cI3SgXRqpdr23cdJtyHWdOU8Y4qxl++OzXlbrXop2SNYs5jX6Y
HKx/xoXlrAZLJ75Ep1wWbbl08nLlZ3hUOzpLGyn6f9nvu92jOZNbi+WMuJf0qgzF5eMBBbclY0Oe
W3dskHRCc6honlWsO+oc1PsT202956Tbk4eLmIz4ltCpnMNH4lYDIiQDQpJa0mtgdIxzZmnAVhs9
iB5//arcrr73pYKUuYtRjD2WsagvwqrgqwGKIqBAgFkoayt00HMeat1Xhj4kICv/Qt4SwAunL5Xx
ixCMiJWWp8bAD98AAPEgOj9qWHhq8HMPdNFq9VjuP74h1QDc33rBI6jilTCM1YvYlICmYL923VX+
Vh/RPU9Xw2mvc0d0fmsJWlJBViOBAnjh5cJAqZqWdIygiy6UbqX9vd7bqvy5HWQ8MFYIaWhzeXQl
bBlbs0LtJCwEFuNUxGKqWJe+jHCLiZNipJ28Sdr/+hsc9DoMVUhoG3OldMdsI1wRRIEm1wW15MXF
iKsbmA6NR4vqklmjQru12FT5exqBOeRTgmfHcst0Y20pXWtFFCiCB1XmOseyrOOYZY0ki1GSVqLp
uSPXqffaGAs4t1K3Zm5y63T6bSpewkalKSwJ9+

F=4000 Hz
Data written to /tmp/comp28512_AhGoes.wav.


<source src="data:audio/wav;base64,UklGRrwJBABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YZgJBAAAADo/eGoPdPVYviHc
3yOoMIzYlGC/Vf7RPcNpR3QJWlYjeOFAqXSMLpT9var8ZDwIaXl0GVvtJBbjYqq+jImTnbz/+vQ6
SGildCNcgSa15IirDo3qkkK7VPmBOYJny3QpXRQoVeayrGWNUZLpuan3Czi3Zut0Kl6lKffn4a3B
jb2RlLj/9ZI25mUFdSZfMyua6RSvI44vkUO3VfQXNRFlGHUdYL8sPutLsIuOp5D2tazymDM2ZCZ1
D2FJLuPsh7H5jiWQrbQE8RcyVmMudfxh0S+J7saybI+oj2ezXe+TMHBiL3XkYlYxMPAKtOaPMo8m
srbtDS+GYSt1xmPYMtjxUbVlkMGO6LAQ7IUtlmAgdaRkWDSB85y265BWjq+vbOr6K6JfD3V8ZdU1
KvXst3aR8Y16rsjobCqoXvl0T2ZPN9T2PrkGkpKNSa0m590oql3cdB1nxjh++JW6nZI5jRysheVL
J6dcuXTlZzs6KfrvuzmT5Yz0quXjtyWeW5B0qGisO9T7Tb3bk5iM0KlH4iIkklpgdGZpGz1//a6+
gpRRjLGoquCKIoBZK3QeaoY+K/8SwC+VEIyWpw/f8SBqWPBz0WruP9UAesHildWLgKZ23VYfT1ev
c35rUkGBAuXCmpagi26l3tu5HTBWaHMlbLNCLARUxFiXcItipEnaGxwMVRtzx2wRRNcFxcUbmEeL
WaO12Hsa5FPHcmNta0WCBzrH45gki1aiI9faGLdSbnL6bcJGLAmxyLGZB4tYoZTVOBeGUQ9yim4U
SNYKK8qEmvGKXqAG1JQVUVCqcRVvZEl/DKjLXJvgimqfe9LwExhPP3Gbb69KKA4ozTqc1Yp6nvPQ
ShLaTc5wGnD2S9APqs4cndGKkJ1tz6MQmUxYcJRwOk13ES/QBJ7Siqqc6c38DlNL228HcXlOHRO3
0fGe2orKm2jMVA0KSllvdXG1T8IUQdPjn+iK75rpyqsLvUjRbt1x7FBmFs3U2qD7ihqabskBCmxH
Q24/ch9SCRhb1tahFYtJmfXHVwgXRq9tm3JOU6sZ7NfXojWLfph/xqwGvkQWbfJyeFRLG3/Z3aNb
i7iXDMUBBWNDd2xCc55V6hwT2+ekh4v4lpzDVgMDQtJrjHPAVogeqtz3pbmLPZYvwqsBoEAoa9Bz
3VckIELeC6fxi4iVxsAAADo/eGoPdPVYviHc3yOoMIzYlGC/Vf7RPcNpR3QJWlYjeOFAqXSMLpT9
var8ZDwIaXl0GVvtJBbjYqq+jImTnbz/+vQ6SGildCNcgSa15IirDo3qkkK7VPmBOYJny3QpXRQo
VeayrGWNUZLpuan3Czi3Zut0Kl6lKffn4a3Bjb2RlLj/9ZI25mUFdSZfMyua6RSvI44vkUO3VfQX
NRFlGHUdYL8sPutLsIuOp5D2tazymDM2ZCZ1D2FJLuPsh7H5jiWQrbQE8RcyVmMudfxh0S+J7say
bI+oj2ezXe+TMHBiL3XkYlYxMPAKtOaPMo8msrbtDS+GYSt1xmPYMtjxUbVlkMGO6LAQ7IUtlmAg
daRkWDSB85y265BWjq+vbOr6K6JfD3V8ZdU1KvXst3aR8Y16rsjobCqoXvl0T2ZPN9T2PrkGkpKN
Sa0m590oql3cdB1nxjh++JW6nZI5jRysheVLJ6dcuXTlZzs6KfrvuzmT5Yz0quXjtyWeW5B0qGis
O9T7Tb3bk5iM0KlH4iIkklpgdGZpGz1//a6+gpRRjLGoquCKIoBZK3QeaoY+K/8SwC+VEIyWpw/f
8SBqWPBz0WruP9UAesHildWLgKZ23VYfT1evc35rUkGBAuXCmpagi26l3tu5HTBWaHMlbLNCLARU
xFiXcItipEnaGxwMVRtzx2wRRNcFxcUbmEeLWaO12Hsa5FPHcmNta0WCBzrH45gki1aiI9faGLdS
bnL6bcJGLAmxyLGZB4tYoZTVOBeGUQ9yim4USNYKK8qEmvGKXqAG1JQVUVCqcRVvZEl/DKjLXJvg
imqfe9LwExhPP3Gbb69KKA4ozTqc1Yp6nvPQShLaTc5wGnD2S9APqs4cndGKkJ1tz6MQmUxYcJRw
Ok13ES/QBJ7Siqqc6c38DlNL228HcXlOHRO30fGe2orKm2jMVA0KSllvdXG1T8IUQdPjn+iK75rp
yqsLvUjRbt1x7FBmFs3U2qD7ihqabskBCmxHQ24/ch9SCRhb1tahFYtJmfXHVwgXRq9tm3JOU6sZ
7NfXojWLfph/xqwGvkQWbfJyeFRLG3/Z3aNbi7iXDMUBBWNDd2xCc55V6hwT2+ekh4v4lpzDVgMD
QtJrjHPAVogeqtz3pbmLPZYvwqsBoEAoa9Bz3VckIELeC6fxi4iVxsAAADo/eGoPdPVYviHc3yOo
MIzYlGC/Vf7RPcNpR3QJWlYjeOFAqXSMLpT9var8ZDwIaXl0GVvtJBbjYqq+jImTnbz/+vQ6SGil
dCNcgSa15IirDo3qkkK7VPmBOYJny3QpXRQoVeayrGWNUZLpuan3Czi3Zut0Kl6lKffn4a3Bjb2R
lLj/9ZI25mUFdSZfMyua6RSvI44vkUO3VfQXNRFlGHUdYL8sPutLsIuOp5D2tazymDM2ZCZ1D2FJ
LuPsh7H5jiWQrbQE8RcyVmMudfxh0S+J7saybI+oj2ezXe+TMHBiL3XkYlYxMPAKtOaPMo8msrbt
DS+GYSt1xmPYMtjxUbVlkMGO6LAQ7IUtlmAgdaRkWDSB85y265BWjq+vbOr6K6JfD3V8ZdU1KvXs
t3aR8Y16rsjobCqoXvl0T2ZPN9T2PrkGkpKNSa0m590oql3cdB1nxjh++JW6nZI5jRysheVLJ6dc
uXTlZzs6KfrvuzmT5Yz0quXjtyWeW5B0qGisO9T7Tb3bk5iM0KlH4iIkklpgdGZpGz1//a6+gpRR
jLGoquCKIoBZK3QeaoY+K/8SwC+VEIyWpw/f8SBqWPBz0WruP9UAesHildWLgKZ23VYfT1evc35r
UkGBAuXCmpagi26l3tu5HTBWaHMlbLNCLARUxFiXcItipEnaGxwMVRtzx2wRRNcFxcUbmEeLWaO1
2Hsa5FPHcmNta0WCBzrH45gki1aiI9faGLdSbnL6bcJGLAmxyLGZB4tYoZTVOBeGUQ9yim4USNYK
K8qEmvGKXqAG1JQVUVCqcRVvZEl/DKjLXJvgimqfe9LwExhPP3Gbb69KKA4ozTqc1Yp6nvPQShLa
Tc5wGnD2S9APqs4cndGKkJ1tz6MQmUxYcJRwOk13ES/QBJ7Siqqc6c38DlNL228HcXlOHRO30fGe
2orKm2jMVA0KSllvdXG1T8IUQdPjn+iK75rpyqsLvUjRbt1x7FBmFs3U2qD7ihqabskBCmxHQ24/
ch9SCRhb1tahFYtJmfXHVwgXRq9tm3JOU6sZ7NfXojWLfph/xqwGvkQWbfJyeFRLG3/Z3aNbi7iX
DMUBBWNDd2xCc55V6hwT2+ekh4v4lpzDVgMDQtJrjHPAVogeqtz3pbmLPZYvwqsBoEAoa9Bz3Vck
IELeC6fxi4iVxsAAADo/eGoPdPVYviHc3yOoMIzYlGC/Vf7RPcNpR3QJWlYjeOFAqXSMLpT9var8
ZDwIaXl0GVvtJBbjYqq+jImTnbz/+vQ6SGildCNcgSa15IirDo3qkkK7VPmBOYJny3QpXRQoVeay
rGWNUZLpuan3Czi3Zut0Kl6lKffn4a3Bjb2RlLj/9ZI25mUFdSZfMyua6RSvI44vkUO3VfQXNRFl
GHUdYL8sPutLsIuOp5D2tazymDM2ZCZ1D2FJLuPsh7H5jiWQrbQE8RcyVmMudfxh0S+J7saybI+o
j2ezXe+TMHBiL3XkYlYxMPAKtOaPMo8msrbtDS

F=8000 Hz
Data written to /tmp/comp28512_tQp14n.wav.


<source src="data:audio/wav;base64,UklGRrwJBABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YZgJBAAAAHhq9Vjc3zCMYL/R
PUd0ViNAqS6UqvwIaRlbFuO+jJ289DqldIEmiKvqklT5gmcpXVXmZY3puQs463SlKeGtvZH/9eZl
Jl+a6SOOQ7cXNRh1vyxLsKeQrPI2ZA9h4+z5jq20FzIuddEvxrKoj13vcGLkYjDw5o8msg0vK3XY
MlG1wY4Q7JZgpGSB8+uQr6/6Kw911TXst/GNyOioXk9m1PYGkkmt3SjcdMY4lbo5jYXlp1zlZyn6
OZP0qrclkHSsO029mIxH4pJaZml//YKUsaiKIit0hj4SwBCMD99qWNFq1QDilYCmVh+vc1JB5cKg
i97bMFYlbCwEWJdipBscG3MRRMXFR4u12ORTY22CB+OYVqLaGG5ywkaxyAeLlNWGUYpu1gqEml6g
lBWqcWRJqMvginvSGE+bbygOOpx6nkoSznD2S6rO0Yptz5lMlHB3EQSeqpz8DttveU630dqKaMwK
SnVxwhTjn++aqwvRbuxQzdT7im7JbEc/cgkY1qFJmVcIr21OU+zXNYt/xr5E8nJLG92juJcBBXds
nlUT24eLnMMDQoxziB73pT2WqwEoa91XQt7xi8bAOj8PdL4hI6jYlFX+w2kJWnjhdIz9vWQ8eXTt
JGKqiZP/+khoI1y15A6NQruBOct0FCiyrFGSqfe3Zipe9+fBjZS4kjYFdTMrFK8vkVX0EWUdYD7r
i472tZgzJnVJLoexJZAE8VZj/GGJ7myPZ7OTMC91VjEKtDKPtu2GYcZj2PFlkOiwhS0gdVg0nLZW
jmzqol98ZSr1dpF6rmwq+XRPNz65ko0m56pdHWd++J2SHKxLJ7l0Ozrvu+WM5eOeW6ho1Pvbk9Cp
IiRgdBs9rr5RjKrggFkeaiv/L5WWp/Eg8HPuP3rB1Yt23U9XfmuBApqWbqW5HWhzs0JUxHCLSdoM
Vcds1wUbmFmjexrHcmtFOsckiyPXt1L6bSwJsZlYoTgXD3IUSCvK8YoG1FFQFW9/DFybap/wEz9x
r0oozdWK89DaTRpw0A8cnZCdoxBYcDpNL9DSiunNU0sHcR0T8Z7Km1QNWW+1T0HT6Irpyr1I3XFm
FtqgGpoBCkNuH1Jb1hWL9ccXRptyqxnXon6YrAYWbXhUf9lbiwzFY0NCc+oc56T4llYD0mvAVqrc
uYsvwqBA0HMkIAuniJUAAHhq9Vjc3zCMYL/RPUd0ViNAqS6UqvwIaRlbFuO+jJ289DqldIEmiKvq
klT5gmcpXVXmZY3puQs463SlKeGtvZH/9eZlJl+a6SOOQ7cXNRh1vyxLsKeQrPI2ZA9h4+z5jq20
FzIuddEvxrKoj13vcGLkYjDw5o8msg0vK3XYMlG1wY4Q7JZgpGSB8+uQr6/6Kw911TXst/GNyOio
Xk9m1PYGkkmt3SjcdMY4lbo5jYXlp1zlZyn6OZP0qrclkHSsO029mIxH4pJaZml//YKUsaiKIit0
hj4SwBCMD99qWNFq1QDilYCmVh+vc1JB5cKgi97bMFYlbCwEWJdipBscG3MRRMXFR4u12ORTY22C
B+OYVqLaGG5ywkaxyAeLlNWGUYpu1gqEml6glBWqcWRJqMvginvSGE+bbygOOpx6nkoSznD2S6rO
0Yptz5lMlHB3EQSeqpz8DttveU630dqKaMwKSnVxwhTjn++aqwvRbuxQzdT7im7JbEc/cgkY1qFJ
mVcIr21OU+zXNYt/xr5E8nJLG92juJcBBXdsnlUT24eLnMMDQoxziB73pT2WqwEoa91XQt7xi8bA
Oj8PdL4hI6jYlFX+w2kJWnjhdIz9vWQ8eXTtJGKqiZP/+khoI1y15A6NQruBOct0FCiyrFGSqfe3
Zipe9+fBjZS4kjYFdTMrFK8vkVX0EWUdYD7ri472tZgzJnVJLoexJZAE8VZj/GGJ7myPZ7OTMC91
VjEKtDKPtu2GYcZj2PFlkOiwhS0gdVg0nLZWjmzqol98ZSr1dpF6rmwq+XRPNz65ko0m56pdHWd+
+J2SHKxLJ7l0Ozrvu+WM5eOeW6ho1Pvbk9CpIiRgdBs9rr5RjKrggFkeaiv/L5WWp/Eg8HPuP3rB
1Yt23U9XfmuBApqWbqW5HWhzs0JUxHCLSdoMVcds1wUbmFmjexrHcmtFOsckiyPXt1L6bSwJsZlY
oTgXD3IUSCvK8YoG1FFQFW9/DFybap/wEz9xr0oozdWK89DaTRpw0A8cnZCdoxBYcDpNL9DSiunN
U0sHcR0T8Z7Km1QNWW+1T0HT6Irpyr1I3XFmFtqgGpoBCkNuH1Jb1hWL9ccXRptyqxnXon6YrAYW
bXhUf9lbiwzFY0NCc+oc56T4llYD0mvAVqrcuYsvwqBA0HMkIAuniJUAAHhq9Vjc3zCMYL/RPUd0
ViNAqS6UqvwIaRlbFuO+jJ289DqldIEmiKvqklT5gmcpXVXmZY3puQs463SlKeGtvZH/9eZlJl+a
6SOOQ7cXNRh1vyxLsKeQrPI2ZA9h4+z5jq20FzIuddEvxrKoj13vcGLkYjDw5o8msg0vK3XYMlG1
wY4Q7JZgpGSB8+uQr6/6Kw911TXst/GNyOioXk9m1PYGkkmt3SjcdMY4lbo5jYXlp1zlZyn6OZP0
qrclkHSsO029mIxH4pJaZml//YKUsaiKIit0hj4SwBCMD99qWNFq1QDilYCmVh+vc1JB5cKgi97b
MFYlbCwEWJdipBscG3MRRMXFR4u12ORTY22CB+OYVqLaGG5ywkaxyAeLlNWGUYpu1gqEml6glBWq
cWRJqMvginvSGE+bbygOOpx6nkoSznD2S6rO0Yptz5lMlHB3EQSeqpz8DttveU630dqKaMwKSnVx
whTjn++aqwvRbuxQzdT7im7JbEc/cgkY1qFJmVcIr21OU+zXNYt/xr5E8nJLG92juJcBBXdsnlUT
24eLnMMDQoxziB73pT2WqwEoa91XQt7xi8bAOj8PdL4hI6jYlFX+w2kJWnjhdIz9vWQ8eXTtJGKq
iZP/+khoI1y15A6NQruBOct0FCiyrFGSqfe3Zipe9+fBjZS4kjYFdTMrFK8vkVX0EWUdYD7ri472
tZgzJnVJLoexJZAE8VZj/GGJ7myPZ7OTMC91VjEKtDKPtu2GYcZj2PFlkOiwhS0gdVg0nLZWjmzq
ol98ZSr1dpF6rmwq+XRPNz65ko0m56pdHWd++J2SHKxLJ7l0Ozrvu+WM5eOeW6ho1Pvbk9CpIiRg
dBs9rr5RjKrggFkeaiv/L5WWp/Eg8HPuP3rB1Yt23U9XfmuBApqWbqW5HWhzs0JUxHCLSdoMVcds
1wUbmFmjexrHcmtFOsckiyPXt1L6bSwJsZlYoTgXD3IUSCvK8YoG1FFQFW9/DFybap/wEz9xr0oo
zdWK89DaTRpw0A8cnZCdoxBYcDpNL9DSiunNU0sHcR0T8Z7Km1QNWW+1T0HT6Irpyr1I3XFmFtqg
GpoBCkNuH1Jb1hWL9ccXRptyqxnXon6YrAYWbXhUf9lbiwzFY0NCc+oc56T4llYD0mvAVqrcuYsv
wqBA0HMkIAuniJUAAHhq9Vjc3zCMYL/RPUd0ViNAqS6UqvwIaRlbFuO+jJ289DqldIEmiKvqklT5
gmcpXVXmZY3puQs463SlKeGtvZH/9eZlJl+a6SOOQ7cXNRh1vyxLsKeQrPI2ZA9h4+z5jq20FzIu
ddEvxrKoj13vcGLkYjDw5o8msg0vK3XYMlG1wY4Q7JZgpGSB8+uQr6/6Kw911TXst/GNyOioXk9m
1PYGkkmt3SjcdMY4lbo5jYXlp1zlZyn6OZP0qrclkHSsO029mIxH4pJaZml//YKUsaiKIit0hj4S
wBCMD99qWNFq1QDilYCmVh+vc1JB5cKgi97bMF

F=16000 Hz
Data written to /tmp/comp28512_UgFjhk.wav.


<source src="data:audio/wav;base64,UklGRrwJBABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YZgJBAAAAPVYMIzRPVYjLpQI
aRbjnbyldIirVPkpXWWNCzilKb2R5mWa6UO3GHVLsKzyD2H5jhcy0S+oj3BiMPAmsit1UbUQ7KRk
65D6K9U18Y2oXtT2Sa3cdJW6heXlZzmTtyWsO5iMklp//bGoK3QSwA/f0WrilVYfUkGgizBWLARi
pBtzxcW12GNt45jaGMJGB4uGUdYKXqCqcajLe9KbbzqcShL2S9GKmUx3Eaqc22+30WjMdXHjn6sL
7FD7imxHCRhJma9t7Nd/xvJy3aMBBZ5Vh4sDQogePZYoa0LexsAPdCOoVf4JWnSMZDztJImTSGi1
5EK7y3SyrKn3Kl7BjZI2MysvkRFlPuv2tSZ1h7EE8fxhbI+TMFYxMo+GYdjx6LAgdZy2bOp8ZXaR
bCpPN5KNql1++BysuXTvu+XjqGjbkyIkGz1RjIBZK/+Wp/BzesF23X5rmpa5HbNCcIsMVdcFWaPH
cjrHI9f6bbGZOBcUSPGKUVB/DGqfP3EozfPQGnAcnaMQOk3SilNLHRPKm1lvQdPpyt1x2qABCh9S
FYsXRqsZfpgWbX/ZDMVCc+ekVgPAVrmLoEAkIIiVeGrc32C/R3RAqar8GVu+jPQ6gSbqkoJnVebp
uet04a3/9SZfI44XNb8sp5A2ZOPsrbQudcayXe/kYuaPDS/YMsGOlmCB86+vD3Xst8joT2YGkt0o
xjg5jadcKfr0qpB0Tb1H4mZpgpSKIoY+EIxqWNUAgKavc+XC3tslbFiXGxwRREeL5FOCB1aibnKx
yJTVim6EmpQVZEngihhPKA56ns5wqs5tz5RwBJ78DnlO2ooKSsIU75rRbs3Ubsk/ctahVwhOUzWL
vkRLG7iXd2wT25zDjHP3pasB3Vfxizo/viHYlMNpeOH9vXl0Yqr/+iNcDo2BORQoUZK3ZvfnlLgF
dRSvVfQdYIuOmDNJLiWQVmOJ7mezL3UKtLbtxmNlkIUtWDRWjqJfKvV6rvl0Prkm5x1nnZJLJzs6
5YyeW9T70KlgdK6+quAeai+V8SDuP9WLT1eBAm6laHNUxEnax2wbmHsaa0Uki7dSLAlYoQ9yK8oG
1BVvXJvwE69K1YraTdAPkJ1YcC/Q6c0HcfGeVA21T+iKvUhmFhqaQ25b1vXHm3LXoqwGeFRbi2ND
6hz4ltJrqtwvwtBzC6cAAPVYMIzRPVYjLpQIaRbjnbyldIirVPkpXWWNCzilKb2R5mWa6UO3GHVL
sKzyD2H5jhcy0S+oj3BiMPAmsit1UbUQ7KRk65D6K9U18Y2oXtT2Sa3cdJW6heXlZzmTtyWsO5iM
klp//bGoK3QSwA/f0WrilVYfUkGgizBWLARipBtzxcW12GNt45jaGMJGB4uGUdYKXqCqcajLe9Kb
bzqcShL2S9GKmUx3Eaqc22+30WjMdXHjn6sL7FD7imxHCRhJma9t7Nd/xvJy3aMBBZ5Vh4sDQoge
PZYoa0LexsAPdCOoVf4JWnSMZDztJImTSGi15EK7y3SyrKn3Kl7BjZI2MysvkRFlPuv2tSZ1h7EE
8fxhbI+TMFYxMo+GYdjx6LAgdZy2bOp8ZXaRbCpPN5KNql1++BysuXTvu+XjqGjbkyIkGz1RjIBZ
K/+Wp/BzesF23X5rmpa5HbNCcIsMVdcFWaPHcjrHI9f6bbGZOBcUSPGKUVB/DGqfP3EozfPQGnAc
naMQOk3SilNLHRPKm1lvQdPpyt1x2qABCh9SFYsXRqsZfpgWbX/ZDMVCc+ekVgPAVrmLoEAkIIiV
eGrc32C/R3RAqar8GVu+jPQ6gSbqkoJnVebpuet04a3/9SZfI44XNb8sp5A2ZOPsrbQudcayXe/k
YuaPDS/YMsGOlmCB86+vD3Xst8joT2YGkt0oxjg5jadcKfr0qpB0Tb1H4mZpgpSKIoY+EIxqWNUA
gKavc+XC3tslbFiXGxwRREeL5FOCB1aibnKxyJTVim6EmpQVZEngihhPKA56ns5wqs5tz5RwBJ78
DnlO2ooKSsIU75rRbs3Ubsk/ctahVwhOUzWLvkRLG7iXd2wT25zDjHP3pasB3Vfxizo/viHYlMNp
eOH9vXl0Yqr/+iNcDo2BORQoUZK3ZvfnlLgFdRSvVfQdYIuOmDNJLiWQVmOJ7mezL3UKtLbtxmNl
kIUtWDRWjqJfKvV6rvl0Prkm5x1nnZJLJzs65YyeW9T70KlgdK6+quAeai+V8SDuP9WLT1eBAm6l
aHNUxEnax2wbmHsaa0Uki7dSLAlYoQ9yK8oG1BVvXJvwE69K1YraTdAPkJ1YcC/Q6c0HcfGeVA21
T+iKvUhmFhqaQ25b1vXHm3LXoqwGeFRbi2ND6hz4ltJrqtwvwtBzC6cAAPVYMIzRPVYjLpQIaRbj
nbyldIirVPkpXWWNCzilKb2R5mWa6UO3GHVLsKzyD2H5jhcy0S+oj3BiMPAmsit1UbUQ7KRk65D6
K9U18Y2oXtT2Sa3cdJW6heXlZzmTtyWsO5iMklp//bGoK3QSwA/f0WrilVYfUkGgizBWLARipBtz
xcW12GNt45jaGMJGB4uGUdYKXqCqcajLe9KbbzqcShL2S9GKmUx3Eaqc22+30WjMdXHjn6sL7FD7
imxHCRhJma9t7Nd/xvJy3aMBBZ5Vh4sDQogePZYoa0LexsAPdCOoVf4JWnSMZDztJImTSGi15EK7
y3SyrKn3Kl7BjZI2MysvkRFlPuv2tSZ1h7EE8fxhbI+TMFYxMo+GYdjx6LAgdZy2bOp8ZXaRbCpP
N5KNql1++BysuXTvu+XjqGjbkyIkGz1RjIBZK/+Wp/BzesF23X5rmpa5HbNCcIsMVdcFWaPHcjrH
I9f6bbGZOBcUSPGKUVB/DGqfP3EozfPQGnAcnaMQOk3SilNLHRPKm1lvQdPpyt1x2qABCh9SFYsX
RqsZfpgWbX/ZDMVCc+ekVgPAVrmLoEAkIIiVeGrc32C/R3RAqar8GVu+jPQ6gSbqkoJnVebpuet0
4a3/9SZfI44XNb8sp5A2ZOPsrbQudcayXe/kYuaPDS/YMsGOlmCB86+vD3Xst8joT2YGkt0oxjg5
jadcKfr0qpB0Tb1H4mZpgpSKIoY+EIxqWNUAgKavc+XC3tslbFiXGxwRREeL5FOCB1aibnKxyJTV
im6EmpQVZEngihhPKA56ns5wqs5tz5RwBJ78DnlO2ooKSsIU75rRbs3Ubsk/ctahVwhOUzWLvkRL
G7iXd2wT25zDjHP3pasB3Vfxizo/viHYlMNpeOH9vXl0Yqr/+iNcDo2BORQoUZK3ZvfnlLgFdRSv
VfQdYIuOmDNJLiWQVmOJ7mezL3UKtLbtxmNlkIUtWDRWjqJfKvV6rvl0Prkm5x1nnZJLJzs65Yye
W9T70KlgdK6+quAeai+V8SDuP9WLT1eBAm6laHNUxEnax2wbmHsaa0Uki7dSLAlYoQ9yK8oG1BVv
XJvwE69K1YraTdAPkJ1YcC/Q6c0HcfGeVA21T+iKvUhmFhqaQ25b1vXHm3LXoqwGeFRbi2ND6hz4
ltJrqtwvwtBzC6cAAPVYMIzRPVYjLpQIaRbjnbyldIirVPkpXWWNCzilKb2R5mWa6UO3GHVLsKzy
D2H5jhcy0S+oj3BiMPAmsit1UbUQ7KRk65D6K9U18Y2oXtT2Sa3cdJW6heXlZzmTtyWsO5iMklp/
/bGoK3QSwA/f0WrilVYfUkGgizBWLARipBtzxcW12GNt45jaGMJGB4uGUdYKXqCqcajLe9Kbbzqc
ShL2S9GKmUx3Eaqc22+30WjMdXHjn6sL7FD7imxHCRhJma9t7Nd/xvJy3aMBBZ5Vh4sDQogePZYo
a0LexsAPdCOoVf4JWnSMZDztJImTSGi15EK7y3

F=18000 Hz
Data written to /tmp/comp28512_aCxB3K.wav.


<source src="data:audio/wav;base64,UklGRrwJBABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YZgJBAAAAO4/2JSvc0CpuR3t
JGKkpXQbmIE5ggfpufptwY2GUZrpBtQdYOCKNmQozQTx9kuoj1hwCrT8DtgyypsgdeOf+itmFnqu
P3IGkhdGfvh/xuVnW4ueWxPbR+LAVlGMKGsSwAAA7j/YlK9zQKm5He0kYqSldBuYgTmCB+m5+m3B
jYZRmukG1B1g4Io2ZCjNBPH2S6iPWHAKtPwO2DLKmyB145/6K2YWeq4/cgaSF0Z++H/G5Wdbi55b
E9tH4sBWUYwoaxLAAADuP9iUr3NAqbkd7SRipKV0G5iBOYIH6bn6bcGNhlGa6QbUHWDgijZkKM0E
8fZLqI9YcAq0/A7YMsqbIHXjn/orZhZ6rj9yBpIXRn74f8blZ1uLnlsT20fiwFZRjChrEsAAAO4/
2JSvc0CpuR3tJGKkpXQbmIE5ggfpufptwY2GUZrpBtQdYOCKNmQozQTx9kuoj1hwCrT8Dtgyypsg
deOf+itmFnquP3IGkhdGfvh/xuVnW4ueWxPbR+LAVlGMKGsSwAAA7j/YlK9zQKm5He0kYqSldBuY
gTmCB+m5+m3BjYZRmukG1B1g4Io2ZCjNBPH2S6iPWHAKtPwO2DLKmyB145/6K2YWeq4/cgaSF0Z+
+H/G5Wdbi55bE9tH4sBWUYwoaxLAAADuP9iUr3NAqbkd7SRipKV0G5iBOYIH6bn6bcGNhlGa6QbU
HWDgijZkKM0E8fZLqI9YcAq0/A7YMsqbIHXjn/orZhZ6rj9yBpIXRn74f8blZ1uLnlsT20fiwFZR
jChrEsAAAO4/2JSvc0CpuR3tJGKkpXQbmIE5ggfpufptwY2GUZrpBtQdYOCKNmQozQTx9kuoj1hw
CrT8DtgyypsgdeOf+itmFnquP3IGkhdGfvh/xuVnW4ueWxPbR+LAVlGMKGsSwAAA7j/YlK9zQKm5
He0kYqSldBuYgTmCB+m5+m3BjYZRmukG1B1g4Io2ZCjNBPH2S6iPWHAKtPwO2DLKmyB145/6K2YW
eq4/cgaSF0Z++H/G5Wdbi55bE9tH4sBWUYwoaxLAAADuP9iUr3NAqbkd7SRipKV0G5iBOYIH6bn6
bcGNhlGa6QbUHWDgijZkKM0E8fZLqI9YcAq0/A7YMsqbIHXjn/orZhZ6rj9yBpIXRn74f8blZ1uL
nlsT20fiwFZRjChrEsAAAO4/2JSvc0CpuR3tJGKkpXQbmIE5ggfpufptwY2GUZrpBtQdYOCKNmQo
zQTx9kuoj1hwCrT8DtgyypsgdeOf+itmFnquP3IGkhdGfvh/xuVnW4ueWxPbR+LAVlGMKGsSwAAA
7j/YlK9zQKm5He0kYqSldBuYgTmCB+m5+m3BjYZRmukG1B1g4Io2ZCjNBPH2S6iPWHAKtPwO2DLK
myB145/6K2YWeq4/cgaSF0Z++H/G5Wdbi55bE9tH4sBWUYwoaxLAAADuP9iUr3NAqbkd7SRipKV0
G5iBOYIH6bn6bcGNhlGa6QbUHWDgijZkKM0E8fZLqI9YcAq0/A7YMsqbIHXjn/orZhZ6rj9yBpIX
Rn74f8blZ1uLnlsT20fiwFZRjChrEsAAAO4/2JSvc0CpuR3tJGKkpXQbmIE5ggfpufptwY2GUZrp
BtQdYOCKNmQozQTx9kuoj1hwCrT8DtgyypsgdeOf+itmFnquP3IGkhdGfvh/xuVnW4ueWxPbR+LA
VlGMKGsSwAAA7j/YlK9zQKm5He0kYqSldBuYgTmCB+m5+m3BjYZRmukG1B1g4Io2ZCjNBPH2S6iP
WHAKtPwO2DLKmyB145/6K2YWeq4/cgaSF0Z++H/G5Wdbi55bE9tH4sBWUYwoaxLAAADuP9iUr3NA
qbkd7SRipKV0G5iBOYIH6bn6bcGNhlGa6QbUHWDgijZkKM0E8fZLqI9YcAq0/A7YMsqbIHXjn/or
ZhZ6rj9yBpIXRn74f8blZ1uLnlsT20fiwFZRjChrEsAAAO4/2JSvc0CpuR3tJGKkpXQbmIE5ggfp
ufptwY2GUZrpBtQdYOCKNmQozQTx9kuoj1hwCrT8DtgyypsgdeOf+itmFnquP3IGkhdGfvh/xuVn
W4ueWxPbR+LAVlGMKGsSwAAA7j/YlK9zQKm5He0kYqSldBuYgTmCB+m5+m3BjYZRmukG1B1g4Io2
ZCjNBPH2S6iPWHAKtPwO2DLKmyB145/6K2YWeq4/cgaSF0Z++H/G5Wdbi55bE9tH4sBWUYwoaxLA
AADuP9iUr3NAqbkd7SRipKV0G5iBOYIH6bn6bcGNhlGa6QbUHWDgijZkKM0E8fZLqI9YcAq0/A7Y
MsqbIHXjn/orZhZ6rj9yBpIXRn74f8blZ1uLnlsT20fiwFZRjChrEsAAAO4/2JSvc0CpuR3tJGKk
pXQbmIE5ggfpufptwY2GUZrpBtQdYOCKNmQozQTx9kuoj1hwCrT8DtgyypsgdeOf+itmFnquP3IG
khdGfvh/xuVnW4ueWxPbR+LAVlGMKGsSwAAA7j/YlK9zQKm5He0kYqSldBuYgTmCB+m5+m3BjYZR
mukG1B1g4Io2ZCjNBPH2S6iPWHAKtPwO2DLKmyB145/6K2YWeq4/cgaSF0Z++H/G5Wdbi55bE9tH
4sBWUYwoaxLAAADuP9iUr3NAqbkd7SRipKV0G5iBOYIH6bn6bcGNhlGa6QbUHWDgijZkKM0E8fZL
qI9YcAq0/A7YMsqbIHXjn/orZhZ6rj9yBpIXRn74f8blZ1uLnlsT20fiwFZRjChrEsAAAO4/2JSv
c0CpuR3tJGKkpXQbmIE5ggfpufptwY2GUZrpBtQdYOCKNmQozQTx9kuoj1hwCrT8DtgyypsgdeOf
+itmFnquP3IGkhdGfvh/xuVnW4ueWxPbR+LAVlGMKGsSwAAA7j/YlK9zQKm5He0kYqSldBuYgTmC
B+m5+m3BjYZRmukG1B1g4Io2ZCjNBPH2S6iPWHAKtPwO2DLKmyB145/6K2YWeq4/cgaSF0Z++H/G
5Wdbi55bE9tH4sBWUYwoaxLAAADuP9iUr3NAqbkd7SRipKV0G5iBOYIH6bn6bcGNhlGa6QbUHWDg
ijZkKM0E8fZLqI9YcAq0/A7YMsqbIHXjn/orZhZ6rj9yBpIXRn74f8blZ1uLnlsT20fiwFZRjChr
EsAAAO4/2JSvc0CpuR3tJGKkpXQbmIE5ggfpufptwY2GUZrpBtQdYOCKNmQozQTx9kuoj1hwCrT8
DtgyypsgdeOf+itmFnquP3IGkhdGfvh/xuVnW4ueWxPbR+LAVlGMKGsSwAAA7j/YlK9zQKm5He0k
YqSldBuYgTmCB+m5+m3BjYZRmukG1B1g4Io2ZCjNBPH2S6iPWHAKtPwO2DLKmyB145/6K2YWeq4/
cgaSF0Z++H/G5Wdbi55bE9tH4sBWUYwoaxLAAADuP9iUr3NAqbkd7SRipKV0G5iBOYIH6bn6bcGN
hlGa6QbUHWDgijZkKM0E8fZLqI9YcAq0/A7YMsqbIHXjn/orZhZ6rj9yBpIXRn74f8blZ1uLnlsT
20fiwFZRjChrEsAAAO4/2JSvc0CpuR3tJGKkpXQbmIE5ggfpufptwY2GUZrpBtQdYOCKNmQozQTx
9kuoj1hwCrT8DtgyypsgdeOf+itmFnquP3IGkhdGfvh/xuVnW4ueWxPbR+LAVlGMKGsSwAAA7j/Y
lK9zQKm5He0kYqSldBuYgTmCB+m5+m3BjYZRmukG1B1g4Io2ZCjNBPH2S6iPWHAKtPwO2DLKmyB1
45/6K2YWeq4/cgaSF0Z++H/G5Wdbi55bE9tH4sBWUYwoaxLAAADuP9iUr3NAqbkd7SRipKV0G5iB
OYIH6bn6bcGNhlGa6QbUHWDgijZkKM0E8fZLqI

F=20000 Hz
Data written to /tmp/comp28512_NAI0hv.wav.


<source src="data:audio/wav;base64,UklGRrwJBABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YZgJBAAAAL4hYL8JWi6UeXS+
jEhoiKuBOVXmqfelKZS4Jl8vkRh1i442ZIexFzKJ7l3vVjEmssZjwY4gdeuQol/st2wq1PYm58Y4
HKzlZ+WMkHTbk5Jarr6KIiv/D9/uP4Cmfmugi2hzWJcMVcXFexqCByPXwkZYoYpu8YqqcVybGE8o
zUoS0A9tzzpNqpwHcdqKWW/jn71IzdQBCgkY9cdOU36Y8nJbi3ds56QDQqrcqwEkIMbA9VjYlEd0
dIwIaWKq9Dq15FT5FCjpuSpevZEFdSOOEWVLsJgz4+wE8dEvZ7PkYjKPK3VlkJZgnLb6Kyr1yOhP
N0mtHWc5jbl0OZOeW029IiR//arghj6Wp9Fq1Yuvc5qWMFZUxBsc1wW12GtFVqL6bQeLD3KEmlFQ
qMvwEygO89D2S5CdlHDSittv8Z4KSkHTqwtmFm7JH1JJmZtyNYsWbd2jY0MT21YDiB4vwt1XiJUP
dDCMw2lAqWQ8FuP/+oEmQrspXVGS63TBjeZlFK8XNT7rrPJJLq20/GGojy915o+GYVG1hS2B82zq
1TV6rk9mko3cdJ2Sp1zvu7cl1PtH4hs9sageahCM8HPilU9X5cK5HSwESdoRRFmjY20ki25ysZmG
USvKlBV/DHvSr0p6nhpw0YpYcASeU0u30VQNwhTpyuxQGpo/chWLr23Xor5Ef9kBBeocnMPAVj2W
0HPxi3hqI6jRPXjhqvztJJ28I1zqkst0ZY23ZuGtkjaa6VX0vyz2tQ9hJZAudWyPcGIKtA0v2PEQ
7Fg0r698ZfGN+XQGkqpdlbpLJyn65eOsO9CpZmlRjCt0L5VqWHrBVh+BAt7bs0JipMdsR4vHcuOY
t1KxyDgX1goG1GRJap+bb9WKznAcnZlML9D8Dh0TaMy1T++a3XH7ikNu1qEXRuzXrAZLGwzFnlX4
loxzuYsoawunOj/c31X+ViP9vRlbiZOldA6NgmeyrAs49+f/9TMrQ7cdYKeQJnX5jlZjxrKTMDDw
tu3YMuiwpGRWjg91dpGoXj653Sh++IXlOzr0qqhomIxgdIKUgFkSwPEg1QB23VJBbqUlbHCLG3Mb
mORTOsfaGCwJlNUUSF6gFW/gij9xOpzaTarOoxB3EenNeU7Km3Vx6IrRbtqgbEdb1lcIqxl/xnhU
uJdCc4eL0mv3paBAQt4AAL4hYL8JWi6UeXS+jEhoiKuBOVXmqfelKZS4Jl8vkRh1i442ZIexFzKJ
7l3vVjEmssZjwY4gdeuQol/st2wq1PYm58Y4HKzlZ+WMkHTbk5Jarr6KIiv/D9/uP4Cmfmugi2hz
WJcMVcXFexqCByPXwkZYoYpu8YqqcVybGE8ozUoS0A9tzzpNqpwHcdqKWW/jn71IzdQBCgkY9cdO
U36Y8nJbi3ds56QDQqrcqwEkIMbA9VjYlEd0dIwIaWKq9Dq15FT5FCjpuSpevZEFdSOOEWVLsJgz
4+wE8dEvZ7PkYjKPK3VlkJZgnLb6Kyr1yOhPN0mtHWc5jbl0OZOeW029IiR//arghj6Wp9Fq1Yuv
c5qWMFZUxBsc1wW12GtFVqL6bQeLD3KEmlFQqMvwEygO89D2S5CdlHDSittv8Z4KSkHTqwtmFm7J
H1JJmZtyNYsWbd2jY0MT21YDiB4vwt1XiJUPdDCMw2lAqWQ8FuP/+oEmQrspXVGS63TBjeZlFK8X
NT7rrPJJLq20/GGojy915o+GYVG1hS2B82zq1TV6rk9mko3cdJ2Sp1zvu7cl1PtH4hs9sageahCM
8HPilU9X5cK5HSwESdoRRFmjY20ki25ysZmGUSvKlBV/DHvSr0p6nhpw0YpYcASeU0u30VQNwhTp
yuxQGpo/chWLr23Xor5Ef9kBBeocnMPAVj2W0HPxi3hqI6jRPXjhqvztJJ28I1zqkst0ZY23ZuGt
kjaa6VX0vyz2tQ9hJZAudWyPcGIKtA0v2PEQ7Fg0r698ZfGN+XQGkqpdlbpLJyn65eOsO9CpZmlR
jCt0L5VqWHrBVh+BAt7bs0JipMdsR4vHcuOYt1KxyDgX1goG1GRJap+bb9WKznAcnZlML9D8Dh0T
aMy1T++a3XH7ikNu1qEXRuzXrAZLGwzFnlX4loxzuYsoawunOj/c31X+ViP9vRlbiZOldA6Ngmey
rAs49+f/9TMrQ7cdYKeQJnX5jlZjxrKTMDDwtu3YMuiwpGRWjg91dpGoXj653Sh++IXlOzr0qqho
mIxgdIKUgFkSwPEg1QB23VJBbqUlbHCLG3MbmORTOsfaGCwJlNUUSF6gFW/gij9xOpzaTarOoxB3
EenNeU7Km3Vx6IrRbtqgbEdb1lcIqxl/xnhUuJdCc4eL0mv3paBAQt4AAL4hYL8JWi6UeXS+jEho
iKuBOVXmqfelKZS4Jl8vkRh1i442ZIexFzKJ7l3vVjEmssZjwY4gdeuQol/st2wq1PYm58Y4HKzl
Z+WMkHTbk5Jarr6KIiv/D9/uP4Cmfmugi2hzWJcMVcXFexqCByPXwkZYoYpu8YqqcVybGE8ozUoS
0A9tzzpNqpwHcdqKWW/jn71IzdQBCgkY9cdOU36Y8nJbi3ds56QDQqrcqwEkIMbA9VjYlEd0dIwI
aWKq9Dq15FT5FCjpuSpevZEFdSOOEWVLsJgz4+wE8dEvZ7PkYjKPK3VlkJZgnLb6Kyr1yOhPN0mt
HWc5jbl0OZOeW029IiR//arghj6Wp9Fq1Yuvc5qWMFZUxBsc1wW12GtFVqL6bQeLD3KEmlFQqMvw
EygO89D2S5CdlHDSittv8Z4KSkHTqwtmFm7JH1JJmZtyNYsWbd2jY0MT21YDiB4vwt1XiJUPdDCM
w2lAqWQ8FuP/+oEmQrspXVGS63TBjeZlFK8XNT7rrPJJLq20/GGojy915o+GYVG1hS2B82zq1TV6
rk9mko3cdJ2Sp1zvu7cl1PtH4hs9sageahCM8HPilU9X5cK5HSwESdoRRFmjY20ki25ysZmGUSvK
lBV/DHvSr0p6nhpw0YpYcASeU0u30VQNwhTpyuxQGpo/chWLr23Xor5Ef9kBBeocnMPAVj2W0HPx
i3hqI6jRPXjhqvztJJ28I1zqkst0ZY23ZuGtkjaa6VX0vyz2tQ9hJZAudWyPcGIKtA0v2PEQ7Fg0
r698ZfGN+XQGkqpdlbpLJyn65eOsO9CpZmlRjCt0L5VqWHrBVh+BAt7bs0JipMdsR4vHcuOYt1Kx
yDgX1goG1GRJap+bb9WKznAcnZlML9D8Dh0TaMy1T++a3XH7ikNu1qEXRuzXrAZLGwzFnlX4loxz
uYsoawunOj/c31X+ViP9vRlbiZOldA6NgmeyrAs49+f/9TMrQ7cdYKeQJnX5jlZjxrKTMDDwtu3Y
MuiwpGRWjg91dpGoXj653Sh++IXlOzr0qqhomIxgdIKUgFkSwPEg1QB23VJBbqUlbHCLG3MbmORT
OsfaGCwJlNUUSF6gFW/gij9xOpzaTarOoxB3EenNeU7Km3Vx6IrRbtqgbEdb1lcIqxl/xnhUuJdC
c4eL0mv3paBAQt4AAL4hYL8JWi6UeXS+jEhoiKuBOVXmqfelKZS4Jl8vkRh1i442ZIexFzKJ7l3v
VjEmssZjwY4gdeuQol/st2wq1PYm58Y4HKzlZ+WMkHTbk5Jarr6KIiv/D9/uP4Cmfmugi2hzWJcM
VcXFexqCByPXwkZYoYpu8YqqcVybGE8ozUoS0A9tzzpNqpwHcdqKWW/jn71IzdQBCgkY9cdOU36Y
8nJbi3ds56QDQqrcqwEkIMbA9VjYlEd0dIwIaWKq9Dq15FT5FCjpuSpevZEFdSOOEWVLsJgz4+wE
8dEvZ7PkYjKPK3VlkJZgnLb6Kyr1yOhPN0mtHW

Part 1.1 Qusetions:
1. Describe the sound produced by a sine-wave of frequency 220 Hz.  
   -It sounds like 'do' in terms of tune.
   
2. How does the sound differ from that produced by musical instruments and the human voice?  
   -Component frequencies of music are discrete and rational with a discernible dominant frequency, they are regular, at least in some part, with a broad frequency range;  
   -Component frequencies of human voice are irregular, and its frequency band is not that wide as music.
   
3. Describe any differences and similarities between the sound at F=220 to F = 440.  
   -Differences: sound at F=440Hz is higher in terms of tune than that at F=220Hz;
   -Similarities: they are all continuous.
   
4. What is the highest frequency you could hear?  
   -16kHz from earphone, 18kHz from microphone
   
5. Could there be other factors that affect your answer to question 4?  
   -Quality of earphone and microphone
   
6. Why is it best not to use ‘for’ loops for this software?  
   -The list we produce is pretty long so using a loop can be time-consuming.

# Part 1.2-Demonstration of aliasing for sine waves

In [5]:
for n in range(1,8):
    print("F=%d Hz"%(500*n))
    playSin(500*n,4000)

F=500 Hz
Data written to /tmp/comp28512_8_7APy.wav.


<source src="data:audio/wav;base64,UklGRuRdAABXQVZFZm10IBAAAAABAAEAoA8AAEAfAAACABAAZGF0YcBdAAAAAN1SMHXdUgAAI63Q
iiOtAADdUjB13VIAACOt0IojrQAA3VIwdd1SAAAjrdCKI60AAN1SMHXdUgAAI63QiiOtAADdUjB1
3VIAACOt0IojrQAA3VIwdd1SAAAjrdCKI60AAN1SMHXdUgAAI63QiiOtAADdUjB13VIAACOt0Ioj
rQAA3VIwdd1SAAAjrdCKI60AAN1SMHXdUgAAI63QiiOtAADdUjB13VIAACOt0IojrQAA3VIwdd1S
AAAjrdCKI60AAN1SMHXdUgAAI63QiiOtAADdUjB13VIAACOt0IojrQAA3VIwdd1SAAAjrdCKI60A
AN1SMHXdUgAAI63QiiOtAADdUjB13VIAACOt0IojrQAA3VIwdd1SAAAjrdCKI60AAN1SMHXdUgAA
I63QiiOtAADdUjB13VIAACOt0IojrQAA3VIwdd1SAAAjrdCKI60AAN1SMHXdUgAAI63QiiOtAADd
UjB13VIAACOt0IojrQAA3VIwdd1SAAAjrdCKI60AAN1SMHXdUgAAI63QiiOtAADdUjB13VIAACOt
0IojrQAA3VIwdd1SAAAjrdCKI60AAN1SMHXdUgAAI63QiiOtAADdUjB13VIAACOt0IojrQAA3VIw
dd1SAAAjrdCKI60AAN1SMHXdUgAAI63QiiOtAADdUjB13VIAACOt0IojrQAA3VIwdd1SAAAjrdCK
I60AAN1SMHXdUgAAI63QiiOtAADdUjB13VIAACOt0IojrQAA3VIwdd1SAAAjrdCKI60AAN1SMHXd
UgAAI63QiiOtAADdUjB13VIAACOt0IojrQAA3VIwdd1SAAAjrdCKI60AAN1SMHXdUgAAI63QiiOt
AADdUjB13VIAACOt0IojrQAA3VIwdd1SAAAjrdCKI60AAN1SMHXdUgAAI63QiiOtAADdUjB13VIA
ACOt0IojrQAA3VIwdd1SAAAjrdCKI60AAN1SMHXdUgAAI63QiiOtAADdUjB13VIAACOt0IojrQAA
3VIwdd1SAAAjrdCKI60AAN1SMHXdUgAAI63QiiOtAADdUjB13VIAACOt0IojrQAA3VIwdd1SAAAj
rdCKI60AAN1SMHXdUgAAI63QiiOtAADdUjB13VIAACOt0IojrQAA3VIwdd1SAAAjrdCKI60AAN1S
MHXdUgAAI63QiiOtAADdUjB13VIAACOt0IojrQAA3VIwdd1SAAAjrdCKI60AAN1SMHXdUgAAI63Q
iiOtAADdUjB13VIAACOt0IojrQAA3VIwdd1SAAAjrdCKI60AAN1SMHXdUgAAI63QiiOtAADdUjB1
3VIAACOt0IojrQAA3VIwdd1SAAAjrdCKI60AAN1SMHXdUgAAI63QiiOtAADdUjB13VIAACOt0Ioj
rQAA3VIwdd1SAAAjrdCKI60AAN1SMHXdUgAAI63QiiOtAADdUjB13VIAACOt0IojrQAA3VIwdd1S
AAAjrdCKI60AAN1SMHXdUgAAI63QiiOtAADdUjB13VIAACOt0IojrQAA3VIwdd1SAAAjrdCKI60A
AN1SMHXdUgAAI63QiiOtAADdUjB13VIAACOt0IojrQAA3VIwdd1SAAAjrdCKI60AAN1SMHXdUgAA
I63QiiOtAADdUjB13VIAACOt0IojrQAA3VIwdd1SAAAjrdCKI60AAN1SMHXdUgAAI63QiiOtAADd
UjB13VIAACOt0IojrQAA3VIwdd1SAAAjrdCKI60AAN1SMHXdUgAAI63QiiOtAADdUjB13VIAACOt
0IojrQAA3VIwdd1SAAAjrdCKI60AAN1SMHXdUgAAI63QiiOtAADdUjB13VIAACOt0IojrQAA3VIw
dd1SAAAjrdCKI60AAN1SMHXdUgAAI63QiiOtAADdUjB13VIAACOt0IojrQAA3VIwdd1SAAAjrdCK
I60AAN1SMHXdUgAAI63QiiOtAADdUjB13VIAACOt0IojrQAA3VIwdd1SAAAjrdCKI60AAN1SMHXd
UgAAI63QiiOtAADdUjB13VIAACOt0IojrQAA3VIwdd1SAAAjrdCKI60AAN1SMHXdUgAAI63QiiOt
AADdUjB13VIAACOt0IojrQAA3VIwdd1SAAAjrdCKI60AAN1SMHXdUgAAI63QiiOtAADdUjB13VIA
ACOt0IojrQAA3VIwdd1SAAAjrdCKI60AAN1SMHXdUgAAI63QiiOtAADdUjB13VIAACOt0IojrQAA
3VIwdd1SAAAjrdCKI60AAN1SMHXdUgAAI63QiiOtAADdUjB13VIAACOt0IojrQAA3VIwdd1SAAAj
rdCKI60AAN1SMHXdUgAAI63QiiOtAADdUjB13VIAACOt0IojrQAA3VIwdd1SAAAjrdCKI60AAN1S
MHXdUgAAI63QiiOtAADdUjB13VIAACOt0IojrQAA3VIwdd1SAAAjrdCKI60AAN1SMHXdUgAAI63Q
iiOtAADdUjB13VIAACOt0IojrQAA3VIwdd1SAAAjrdCKI60AAN1SMHXdUgAAI63QiiOtAADdUjB1
3VIAACOt0IojrQAA3VIwdd1SAAAjrdCKI60AAN1SMHXdUgAAI63QiiOtAADdUjB13VIAACOt0Ioj
rQAA3VIwdd1SAAAjrdCKI60AAN1SMHXdUgAAI63QiiOtAADdUjB13VIAACOt0IojrQAA3VIwdd1S
AAAjrdCKI60AAN1SMHXdUgAAI63QiiOtAADdUjB13VIAACOt0IojrQAA3VIwdd1SAAAjrdCKI60A
AN1SMHXdUgAAI63QiiOtAADdUjB13VIAACOt0IojrQAA3VIwdd1SAAAjrdCKI60AAN1SMHXdUgAA
I63QiiOtAADdUjB13VIAACOt0IojrQAA3VIwdd1SAAAjrdCKI60AAN1SMHXdUgAAI63QiiOtAADd
UjB13VIAACOt0IojrQAA3VIwdd1SAAAjrdCKI60AAN1SMHXdUgAAI63QiiOtAADdUjB13VIAACOt
0IojrQAA3VIwdd1SAAAjrdCKI60AAN1SMHXdUgAAI63QiiOtAADdUjB13VIAACOt0IojrQAA3VIw
dd1SAAAjrdCKI60AAN1SMHXdUgAAI63QiiOtAADdUjB13VIAACOt0IojrQAA3VIwdd1SAAAjrdCK
I60AAN1SMHXdUgAAI63QiiOtAADdUjB13VIAACOt0IojrQAA3VIwdd1SAAAjrdCKI60AAN1SMHXd
UgAAI63QiiOtAADdUjB13VIAACOt0IojrQAA3VIwdd1SAAAjrdCKI60AAN1SMHXdUgAAI63QiiOt
AADdUjB13VIAACOt0IojrQAA3VIwdd1SAAAjrdCKI60AAN1SMHXdUgAAI63QiiOtAADdUjB13VIA
ACOt0IojrQAA3VIwdd1SAAAjrdCKI60AAN1SMHXdUgAAI63QiiOtAADdUjB13VIAACOt0IojrQAA
3VIwdd1SAAAjrdCKI60AAN1SMHXdUgAAI63QiiOtAADdUjB13VIAACOt0IojrQAA3VIwdd1SAAAj
rdCKI60AAN1SMHXdUgAAI63QiiOtAADdUjB13VIAACOt0IojrQAA3VIwdd1SAAAjrdCKI60AAN1S
MHXdUgAAI63QiiOtAADdUjB13VIAACOt0IojrQAA3VIwdd1SAAAjrdCKI60AAN1SMHXdUgAAI63Q
iiOtAADdUjB13VIAACOt0IojrQAA3VIwdd1SAAAjrdCKI60AAN1SMHXdUgAAI63QiiOtAADdUjB1
3VIAACOt0IojrQAA3VIwdd1SAAAjrdCKI60AAN1SMHXdUgAAI63QiiOtAADdUjB13VIAACOt0Ioj
rQAA3VIwdd1SAAAjrdCKI60AAN1SMHXdUgAAI6

F=1000 Hz
Data written to /tmp/comp28512_AVLMLC.wav.


<source src="data:audio/wav;base64,UklGRuRdAABXQVZFZm10IBAAAAABAAEAoA8AAEAfAAACABAAZGF0YcBdAAAAADB1AADQigAAMHUA
ANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA
0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQ
igAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCK
AAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoA
ADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAA
MHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAw
dQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1
AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUA
ANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA
0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQ
igAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCK
AAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoA
ADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAA
MHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAw
dQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1
AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUA
ANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA
0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQ
igAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCK
AAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoA
ADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAA
MHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAw
dQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1
AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUA
ANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA
0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQ
igAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCK
AAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoA
ADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAA
MHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAw
dQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1
AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUA
ANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA
0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQ
igAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCK
AAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoA
ADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAA
MHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAw
dQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1
AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUA
ANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA
0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQ
igAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCK
AAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoA
ADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAA
MHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAw
dQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1
AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUA
ANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA
0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQ
igAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMH

F=1500 Hz
Data written to /tmp/comp28512_1Et10T.wav.


<source src="data:audio/wav;base64,UklGRuRdAABXQVZFZm10IBAAAAABAAEAoA8AAEAfAAACABAAZGF0YcBdAAAAAN1S0IrdUgAAI60w
dSOtAADdUtCK3VIAACOtMHUjrQAA3VLQit1SAAAjrTB1I60AAN1S0IrdUgAAI60wdSOtAADdUtCK
3VIAACOtMHUjrQAA3VLQit1SAAAjrTB1I60AAN1S0IrdUgAAI60wdSOtAADdUtCK3VIAACOtMHUj
rQAA3VLQit1SAAAjrTB1I60AAN1S0IrdUgAAI60wdSOtAADdUtCK3VIAACOtMHUjrQAA3VLQit1S
AAAjrTB1I60AAN1S0IrdUgAAI60wdSOtAADdUtCK3VIAACOtMHUjrQAA3VLQit1SAAAjrTB1I60A
AN1S0IrdUgAAI60wdSOtAADdUtCK3VIAACOtMHUjrQAA3VLQit1SAAAjrTB1I60AAN1S0IrdUgAA
I60wdSOtAADdUtCK3VIAACOtMHUjrQAA3VLQit1SAAAjrTB1I60AAN1S0IrdUgAAI60wdSOtAADd
UtCK3VIAACOtMHUjrQAA3VLQit1SAAAjrTB1I60AAN1S0IrdUgAAI60wdSOtAADdUtCK3VIAACOt
MHUjrQAA3VLQit1SAAAjrTB1I60AAN1S0IrdUgAAI60wdSOtAADdUtCK3VIAACOtMHUjrQAA3VLQ
it1SAAAjrTB1I60AAN1S0IrdUgAAI60wdSOtAADdUtCK3VIAACOtMHUjrQAA3VLQit1SAAAjrTB1
I60AAN1S0IrdUgAAI60wdSOtAADdUtCK3VIAACOtMHUjrQAA3VLQit1SAAAjrTB1I60AAN1S0Ird
UgAAI60wdSOtAADdUtCK3VIAACOtMHUjrQAA3VLQit1SAAAjrTB1I60AAN1S0IrdUgAAI60wdSOt
AADdUtCK3VIAACOtMHUjrQAA3VLQit1SAAAjrTB1I60AAN1S0IrdUgAAI60wdSOtAADdUtCK3VIA
ACOtMHUjrQAA3VLQit1SAAAjrTB1I60AAN1S0IrdUgAAI60wdSOtAADdUtCK3VIAACOtMHUjrQAA
3VLQit1SAAAjrTB1I60AAN1S0IrdUgAAI60wdSOtAADdUtCK3VIAACOtMHUjrQAA3VLQit1SAAAj
rTB1I60AAN1S0IrdUgAAI60wdSOtAADdUtCK3VIAACOtMHUjrQAA3VLQit1SAAAjrTB1I60AAN1S
0IrdUgAAI60wdSOtAADdUtCK3VIAACOtMHUjrQAA3VLQit1SAAAjrTB1I60AAN1S0IrdUgAAI60w
dSOtAADdUtCK3VIAACOtMHUjrQAA3VLQit1SAAAjrTB1I60AAN1S0IrdUgAAI60wdSOtAADdUtCK
3VIAACOtMHUjrQAA3VLQit1SAAAjrTB1I60AAN1S0IrdUgAAI60wdSOtAADdUtCK3VIAACOtMHUj
rQAA3VLQit1SAAAjrTB1I60AAN1S0IrdUgAAI60wdSOtAADdUtCK3VIAACOtMHUjrQAA3VLQit1S
AAAjrTB1I60AAN1S0IrdUgAAI60wdSOtAADdUtCK3VIAACOtMHUjrQAA3VLQit1SAAAjrTB1I60A
AN1S0IrdUgAAI60wdSOtAADdUtCK3VIAACOtMHUjrQAA3VLQit1SAAAjrTB1I60AAN1S0IrdUgAA
I60wdSOtAADdUtCK3VIAACOtMHUjrQAA3VLQit1SAAAjrTB1I60AAN1S0IrdUgAAI60wdSOtAADd
UtCK3VIAACOtMHUjrQAA3VLQit1SAAAjrTB1I60AAN1S0IrdUgAAI60wdSOtAADdUtCK3VIAACOt
MHUjrQAA3VLQit1SAAAjrTB1I60AAN1S0IrdUgAAI60wdSOtAADdUtCK3VIAACOtMHUjrQAA3VLQ
it1SAAAjrTB1I60AAN1S0IrdUgAAI60wdSOtAADdUtCK3VIAACOtMHUjrQAA3VLQit1SAAAjrTB1
I60AAN1S0IrdUgAAI60wdSOtAADdUtCK3VIAACOtMHUjrQAA3VLQit1SAAAjrTB1I60AAN1S0Ird
UgAAI60wdSOtAADdUtCK3VIAACOtMHUjrQAA3VLQit1SAAAjrTB1I60AAN1S0IrdUgAAI60wdSOt
AADdUtCK3VIAACOtMHUjrQAA3VLQit1SAAAjrTB1I60AAN1S0IrdUgAAI60wdSOtAADdUtCK3VIA
ACOtMHUjrQAA3VLQit1SAAAjrTB1I60AAN1S0IrdUgAAI60wdSOtAADdUtCK3VIAACOtMHUjrQAA
3VLQit1SAAAjrTB1I60AAN1S0IrdUgAAI60wdSOtAADdUtCK3VIAACOtMHUjrQAA3VLQit1SAAAj
rTB1I60AAN1S0IrdUgAAI60wdSOtAADdUtCK3VIAACOtMHUjrQAA3VLQit1SAAAjrTB1I60AAN1S
0IrdUgAAI60wdSOtAADdUtCK3VIAACOtMHUjrQAA3VLQit1SAAAjrTB1I60AAN1S0IrdUgAAI60w
dSOtAADdUtCK3VIAACOtMHUjrQAA3VLQit1SAAAjrTB1I60AAN1S0IrdUgAAI60wdSOtAADdUtCK
3VIAACOtMHUjrQAA3VLQit1SAAAjrTB1I60AAN1S0IrdUgAAI60wdSOtAADdUtCK3VIAACOtMHUj
rQAA3VLQit1SAAAjrTB1I60AAN1S0IrdUgAAI60wdSOtAADdUtCK3VIAACOtMHUjrQAA3VLQit1S
AAAjrTB1I60AAN1S0IrdUgAAI60wdSOtAADdUtCK3VIAACOtMHUjrQAA3VLQit1SAAAjrTB1I60A
AN1S0IrdUgAAI60wdSOtAADdUtCK3VIAACOtMHUjrQAA3VLQit1SAAAjrTB1I60AAN1S0IrdUgAA
I60wdSOtAADdUtCK3VIAACOtMHUjrQAA3VLQit1SAAAjrTB1I60AAN1S0IrdUgAAI60wdSOtAADd
UtCK3VIAACOtMHUjrQAA3VLQit1SAAAjrTB1I60AAN1S0IrdUgAAI60wdSOtAADdUtCK3VIAACOt
MHUjrQAA3VLQit1SAAAjrTB1I60AAN1S0IrdUgAAI60wdSOtAADdUtCK3VIAACOtMHUjrQAA3VLQ
it1SAAAjrTB1I60AAN1S0IrdUgAAI60wdSOtAADdUtCK3VIAACOtMHUjrQAA3VLQit1SAAAjrTB1
I60AAN1S0IrdUgAAI60wdSOtAADdUtCK3VIAACOtMHUjrQAA3VLQit1SAAAjrTB1I60AAN1S0Ird
UgAAI60wdSOtAADdUtCK3VIAACOtMHUjrQAA3VLQit1SAAAjrTB1I60AAN1S0IrdUgAAI60wdSOt
AADdUtCK3VIAACOtMHUjrQAA3VLQit1SAAAjrTB1I60AAN1S0IrdUgAAI60wdSOtAADdUtCK3VIA
ACOtMHUjrQAA3VLQit1SAAAjrTB1I60AAN1S0IrdUgAAI60wdSOtAADdUtCK3VIAACOtMHUjrQAA
3VLQit1SAAAjrTB1I60AAN1S0IrdUgAAI60wdSOtAADdUtCK3VIAACOtMHUjrQAA3VLQit1SAAAj
rTB1I60AAN1S0IrdUgAAI60wdSOtAADdUtCK3VIAACOtMHUjrQAA3VLQit1SAAAjrTB1I60AAN1S
0IrdUgAAI60wdSOtAADdUtCK3VIAACOtMHUjrQAA3VLQit1SAAAjrTB1I60AAN1S0IrdUgAAI60w
dSOtAADdUtCK3VIAACOtMHUjrQAA3VLQit1SAAAjrTB1I60AAN1S0IrdUgAAI60wdSOtAADdUtCK
3VIAACOtMHUjrQAA3VLQit1SAAAjrTB1I60AAN1S0IrdUgAAI60wdSOtAADdUtCK3VIAACOtMHUj
rQAA3VLQit1SAAAjrTB1I60AAN1S0IrdUgAAI6

F=2000 Hz
Data written to /tmp/comp28512_BCtoWQ.wav.


<source src="data:audio/wav;base64,UklGRuRdAABXQVZFZm10IBAAAAABAAEAoA8AAEAfAAACABAAZGF0YcBdAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

F=2500 Hz
Data written to /tmp/comp28512_NPzrs8.wav.


<source src="data:audio/wav;base64,UklGRuRdAABXQVZFZm10IBAAAAABAAEAoA8AAEAfAAACABAAZGF0YcBdAAAAACOtMHUjrQAA3VLQ
it1SAAAjrTB1I60AAN1S0IrdUgAAI60wdSOtAADdUtCK3VIAACOtMHUjrQAA3VLQit1SAAAjrTB1
I60AAN1S0IrdUgAAI60wdSOtAADdUtCK3VIAACOtMHUjrQAA3VLQit1SAAAjrTB1I60AAN1S0Ird
UgAAI60wdSOtAADdUtCK3VIAACOtMHUjrQAA3VLQit1SAAAjrTB1I60AAN1S0IrdUgAAI60wdSOt
AADdUtCK3VIAACOtMHUjrQAA3VLQit1SAAAjrTB1I60AAN1S0IrdUgAAI60wdSOtAADdUtCK3VIA
ACOtMHUjrQAA3VLQit1SAAAjrTB1I60AAN1S0IrdUgAAI60wdSOtAADdUtCK3VIAACOtMHUjrQAA
3VLQit1SAAAjrTB1I60AAN1S0IrdUgAAI60wdSOtAADdUtCK3VIAACOtMHUjrQAA3VLQit1SAAAj
rTB1I60AAN1S0IrdUgAAI60wdSOtAADdUtCK3VIAACOtMHUjrQAA3VLQit1SAAAjrTB1I60AAN1S
0IrdUgAAI60wdSOtAADdUtCK3VIAACOtMHUjrQAA3VLQit1SAAAjrTB1I60AAN1S0IrdUgAAI60w
dSOtAADdUtCK3VIAACOtMHUjrQAA3VLQit1SAAAjrTB1I60AAN1S0IrdUgAAI60wdSOtAADdUtCK
3VIAACOtMHUjrQAA3VLQit1SAAAjrTB1I60AAN1S0IrdUgAAI60wdSOtAADdUtCK3VIAACOtMHUj
rQAA3VLQit1SAAAjrTB1I60AAN1S0IrdUgAAI60wdSOtAADdUtCK3VIAACOtMHUjrQAA3VLQit1S
AAAjrTB1I60AAN1S0IrdUgAAI60wdSOtAADdUtCK3VIAACOtMHUjrQAA3VLQit1SAAAjrTB1I60A
AN1S0IrdUgAAI60wdSOtAADdUtCK3VIAACOtMHUjrQAA3VLQit1SAAAjrTB1I60AAN1S0IrdUgAA
I60wdSOtAADdUtCK3VIAACOtMHUjrQAA3VLQit1SAAAjrTB1I60AAN1S0IrdUgAAI60wdSOtAADd
UtCK3VIAACOtMHUjrQAA3VLQit1SAAAjrTB1I60AAN1S0IrdUgAAI60wdSOtAADdUtCK3VIAACOt
MHUjrQAA3VLQit1SAAAjrTB1I60AAN1S0IrdUgAAI60wdSOtAADdUtCK3VIAACOtMHUjrQAA3VLQ
it1SAAAjrTB1I60AAN1S0IrdUgAAI60wdSOtAADdUtCK3VIAACOtMHUjrQAA3VLQit1SAAAjrTB1
I60AAN1S0IrdUgAAI60wdSOtAADdUtCK3VIAACOtMHUjrQAA3VLQit1SAAAjrTB1I60AAN1S0Ird
UgAAI60wdSOtAADdUtCK3VIAACOtMHUjrQAA3VLQit1SAAAjrTB1I60AAN1S0IrdUgAAI60wdSOt
AADdUtCK3VIAACOtMHUjrQAA3VLQit1SAAAjrTB1I60AAN1S0IrdUgAAI60wdSOtAADdUtCK3VIA
ACOtMHUjrQAA3VLQit1SAAAjrTB1I60AAN1S0IrdUgAAI60wdSOtAADdUtCK3VIAACOtMHUjrQAA
3VLQit1SAAAjrTB1I60AAN1S0IrdUgAAI60wdSOtAADdUtCK3VIAACOtMHUjrQAA3VLQit1SAAAj
rTB1I60AAN1S0IrdUgAAI60wdSOtAADdUtCK3VIAACOtMHUjrQAA3VLQit1SAAAjrTB1I60AAN1S
0IrdUgAAI60wdSOtAADdUtCK3VIAACOtMHUjrQAA3VLQit1SAAAjrTB1I60AAN1S0IrdUgAAI60w
dSOtAADdUtCK3VIAACOtMHUjrQAA3VLQit1SAAAjrTB1I60AAN1S0IrdUgAAI60wdSOtAADdUtCK
3VIAACOtMHUjrQAA3VLQit1SAAAjrTB1I60AAN1S0IrdUgAAI60wdSOtAADdUtCK3VIAACOtMHUj
rQAA3VLQit1SAAAjrTB1I60AAN1S0IrdUgAAI60wdSOtAADdUtCK3VIAACOtMHUjrQAA3VLQit1S
AAAjrTB1I60AAN1S0IrdUgAAI60wdSOtAADdUtCK3VIAACOtMHUjrQAA3VLQit1SAAAjrTB1I60A
AN1S0IrdUgAAI60wdSOtAADdUtCK3VIAACOtMHUjrQAA3VLQit1SAAAjrTB1I60AAN1S0IrdUgAA
I60wdSOtAADdUtCK3VIAACOtMHUjrQAA3VLQit1SAAAjrTB1I60AAN1S0IrdUgAAI60wdSOtAADd
UtCK3VIAACOtMHUjrQAA3VLQit1SAAAjrTB1I60AAN1S0IrdUgAAI60wdSOtAADdUtCK3VIAACOt
MHUjrQAA3VLQit1SAAAjrTB1I60AAN1S0IrdUgAAI60wdSOtAADdUtCK3VIAACOtMHUjrQAA3VLQ
it1SAAAjrTB1I60AAN1S0IrdUgAAI60wdSOtAADdUtCK3VIAACOtMHUjrQAA3VLQit1SAAAjrTB1
I60AAN1S0IrdUgAAI60wdSOtAADdUtCK3VIAACOtMHUjrQAA3VLQit1SAAAjrTB1I60AAN1S0Ird
UgAAI60wdSOtAADdUtCK3VIAACOtMHUjrQAA3VLQit1SAAAjrTB1I60AAN1S0IrdUgAAI60wdSOt
AADdUtCK3VIAACOtMHUjrQAA3VLQit1SAAAjrTB1I60AAN1S0IrdUgAAI60wdSOtAADdUtCK3VIA
ACOtMHUjrQAA3VLQit1SAAAjrTB1I60AAN1S0IrdUgAAI60wdSOtAADdUtCK3VIAACOtMHUjrQAA
3VLQit1SAAAjrTB1I60AAN1S0IrdUgAAI60wdSOtAADdUtCK3VIAACOtMHUjrQAA3VLQit1SAAAj
rTB1I60AAN1S0IrdUgAAI60wdSOtAADdUtCK3VIAACOtMHUjrQAA3VLQit1SAAAjrTB1I60AAN1S
0IrdUgAAI60wdSOtAADdUtCK3VIAACOtMHUjrQAA3VLQit1SAAAjrTB1I60AAN1S0IrdUgAAI60w
dSOtAADdUtCK3VIAACOtMHUjrQAA3VLQit1SAAAjrTB1I60AAN1S0IrdUgAAI60wdSOtAADdUtCK
3VIAACOtMHUjrQAA3VLQit1SAAAjrTB1I60AAN1S0IrdUgAAI60wdSOtAADdUtCK3VIAACOtMHUj
rQAA3VLQit1SAAAjrTB1I60AAN1S0IrdUgAAI60wdSOtAADdUtCK3VIAACOtMHUjrQAA3VLQit1S
AAAjrTB1I60AAN1S0IrdUgAAI60wdSOtAADdUtCK3VIAACOtMHUjrQAA3VLQit1SAAAjrTB1I60A
AN1S0IrdUgAAI60wdSOtAADdUtCK3VIAACOtMHUjrQAA3VLQit1SAAAjrTB1I60AAN1S0IrdUgAA
I60wdSOtAADdUtCK3VIAACOtMHUjrQAA3VLQit1SAAAjrTB1I60AAN1S0IrdUgAAI60wdSOtAADd
UtCK3VIAACOtMHUjrQAA3VLQit1SAAAjrTB1I60AAN1S0IrdUgAAI60wdSOtAADdUtCK3VIAACOt
MHUjrQAA3VLQit1SAAAjrTB1I60AAN1S0IrdUgAAI60wdSOtAADdUtCK3VIAACOtMHUjrQAA3VLQ
it1SAAAjrTB1I60AAN1S0IrdUgAAI60wdSOtAADdUtCK3VIAACOtMHUjrQAA3VLQit1SAAAjrTB1
I60AAN1S0IrdUgAAI60wdSOtAADdUtCK3VIAACOtMHUjrQAA3VLQit1SAAAjrTB1I60AAN1S0Ird
UgAAI60wdSOtAADdUtCK3VIAACOtMHUjrQAA3V

F=3000 Hz
Data written to /tmp/comp28512_rFybjH.wav.


<source src="data:audio/wav;base64,UklGRuRdAABXQVZFZm10IBAAAAABAAEAoA8AAEAfAAACABAAZGF0YcBdAAAAANCKAAAwdQAA0IoA
ADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAA
MHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAw
dQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1
AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUA
ANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA
0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQ
igAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCK
AAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoA
ADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAA
MHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAw
dQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1
AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUA
ANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA
0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQ
igAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCK
AAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoA
ADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAA
MHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAw
dQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1
AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUA
ANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA
0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQ
igAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCK
AAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoA
ADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAA
MHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAw
dQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1
AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUA
ANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA
0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQ
igAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCK
AAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoA
ADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAA
MHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAw
dQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1
AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUA
ANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA
0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQ
igAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCK
AAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoA
ADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAA
MHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAw
dQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1
AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUA
ANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA
0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQ
igAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCK
AAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoA
ADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAA
MHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0IoAADB1AADQigAAMHUAANCKAAAw
dQAA0IoAADB1AADQigAAMHUAANCKAAAwdQAA0I

F=3500 Hz
Data written to /tmp/comp28512_ziJqqW.wav.


<source src="data:audio/wav;base64,UklGRuRdAABXQVZFZm10IBAAAAABAAEAoA8AAEAfAAACABAAZGF0YcBdAAAAACOt0IojrQAA3VIw
dd1SAAAjrdCKI60AAN1SMHXdUgAAI63QiiOtAADdUjB13VIAACOt0IojrQAA3VIwdd1SAAAjrdCK
I60AAN1SMHXdUgAAI63QiiOtAADdUjB13VIAACOt0IojrQAA3VIwdd1SAAAjrdCKI60AAN1SMHXd
UgAAI63QiiOtAADdUjB13VIAACOt0IojrQAA3VIwdd1SAAAjrdCKI60AAN1SMHXdUgAAI63QiiOt
AADdUjB13VIAACOt0IojrQAA3VIwdd1SAAAjrdCKI60AAN1SMHXdUgAAI63QiiOtAADdUjB13VIA
ACOt0IojrQAA3VIwdd1SAAAjrdCKI60AAN1SMHXdUgAAI63QiiOtAADdUjB13VIAACOt0IojrQAA
3VIwdd1SAAAjrdCKI60AAN1SMHXdUgAAI63QiiOtAADdUjB13VIAACOt0IojrQAA3VIwdd1SAAAj
rdCKI60AAN1SMHXdUgAAI63QiiOtAADdUjB13VIAACOt0IojrQAA3VIwdd1SAAAjrdCKI60AAN1S
MHXdUgAAI63QiiOtAADdUjB13VIAACOt0IojrQAA3VIwdd1SAAAjrdCKI60AAN1SMHXdUgAAI63Q
iiOtAADdUjB13VIAACOt0IojrQAA3VIwdd1SAAAjrdCKI60AAN1SMHXdUgAAI63QiiOtAADdUjB1
3VIAACOt0IojrQAA3VIwdd1SAAAjrdCKI60AAN1SMHXdUgAAI63QiiOtAADdUjB13VIAACOt0Ioj
rQAA3VIwdd1SAAAjrdCKI60AAN1SMHXdUgAAI63QiiOtAADdUjB13VIAACOt0IojrQAA3VIwdd1S
AAAjrdCKI60AAN1SMHXdUgAAI63QiiOtAADdUjB13VIAACOt0IojrQAA3VIwdd1SAAAjrdCKI60A
AN1SMHXdUgAAI63QiiOtAADdUjB13VIAACOt0IojrQAA3VIwdd1SAAAjrdCKI60AAN1SMHXdUgAA
I63QiiOtAADdUjB13VIAACOt0IojrQAA3VIwdd1SAAAjrdCKI60AAN1SMHXdUgAAI63QiiOtAADd
UjB13VIAACOt0IojrQAA3VIwdd1SAAAjrdCKI60AAN1SMHXdUgAAI63QiiOtAADdUjB13VIAACOt
0IojrQAA3VIwdd1SAAAjrdCKI60AAN1SMHXdUgAAI63QiiOtAADdUjB13VIAACOt0IojrQAA3VIw
dd1SAAAjrdCKI60AAN1SMHXdUgAAI63QiiOtAADdUjB13VIAACOt0IojrQAA3VIwdd1SAAAjrdCK
I60AAN1SMHXdUgAAI63QiiOtAADdUjB13VIAACOt0IojrQAA3VIwdd1SAAAjrdCKI60AAN1SMHXd
UgAAI63QiiOtAADdUjB13VIAACOt0IojrQAA3VIwdd1SAAAjrdCKI60AAN1SMHXdUgAAI63QiiOt
AADdUjB13VIAACOt0IojrQAA3VIwdd1SAAAjrdCKI60AAN1SMHXdUgAAI63QiiOtAADdUjB13VIA
ACOt0IojrQAA3VIwdd1SAAAjrdCKI60AAN1SMHXdUgAAI63QiiOtAADdUjB13VIAACOt0IojrQAA
3VIwdd1SAAAjrdCKI60AAN1SMHXdUgAAI63QiiOtAADdUjB13VIAACOt0IojrQAA3VIwdd1SAAAj
rdCKI60AAN1SMHXdUgAAI63QiiOtAADdUjB13VIAACOt0IojrQAA3VIwdd1SAAAjrdCKI60AAN1S
MHXdUgAAI63QiiOtAADdUjB13VIAACOt0IojrQAA3VIwdd1SAAAjrdCKI60AAN1SMHXdUgAAI63Q
iiOtAADdUjB13VIAACOt0IojrQAA3VIwdd1SAAAjrdCKI60AAN1SMHXdUgAAI63QiiOtAADdUjB1
3VIAACOt0IojrQAA3VIwdd1SAAAjrdCKI60AAN1SMHXdUgAAI63QiiOtAADdUjB13VIAACOt0Ioj
rQAA3VIwdd1SAAAjrdCKI60AAN1SMHXdUgAAI63QiiOtAADdUjB13VIAACOt0IojrQAA3VIwdd1S
AAAjrdCKI60AAN1SMHXdUgAAI63QiiOtAADdUjB13VIAACOt0IojrQAA3VIwdd1SAAAjrdCKI60A
AN1SMHXdUgAAI63QiiOtAADdUjB13VIAACOt0IojrQAA3VIwdd1SAAAjrdCKI60AAN1SMHXdUgAA
I63QiiOtAADdUjB13VIAACOt0IojrQAA3VIwdd1SAAAjrdCKI60AAN1SMHXdUgAAI63QiiOtAADd
UjB13VIAACOt0IojrQAA3VIwdd1SAAAjrdCKI60AAN1SMHXdUgAAI63QiiOtAADdUjB13VIAACOt
0IojrQAA3VIwdd1SAAAjrdCKI60AAN1SMHXdUgAAI63QiiOtAADdUjB13VIAACOt0IojrQAA3VIw
dd1SAAAjrdCKI60AAN1SMHXdUgAAI63QiiOtAADdUjB13VIAACOt0IojrQAA3VIwdd1SAAAjrdCK
I60AAN1SMHXdUgAAI63QiiOtAADdUjB13VIAACOt0IojrQAA3VIwdd1SAAAjrdCKI60AAN1SMHXd
UgAAI63QiiOtAADdUjB13VIAACOt0IojrQAA3VIwdd1SAAAjrdCKI60AAN1SMHXdUgAAI63QiiOt
AADdUjB13VIAACOt0IojrQAA3VIwdd1SAAAjrdCKI60AAN1SMHXdUgAAI63QiiOtAADdUjB13VIA
ACOt0IojrQAA3VIwdd1SAAAjrdCKI60AAN1SMHXdUgAAI63QiiOtAADdUjB13VIAACOt0IojrQAA
3VIwdd1SAAAjrdCKI60AAN1SMHXdUgAAI63QiiOtAADdUjB13VIAACOt0IojrQAA3VIwdd1SAAAj
rdCKI60AAN1SMHXdUgAAI63QiiOtAADdUjB13VIAACOt0IojrQAA3VIwdd1SAAAjrdCKI60AAN1S
MHXdUgAAI63QiiOtAADdUjB13VIAACOt0IojrQAA3VIwdd1SAAAjrdCKI60AAN1SMHXdUgAAI63Q
iiOtAADdUjB13VIAACOt0IojrQAA3VIwdd1SAAAjrdCKI60AAN1SMHXdUgAAI63QiiOtAADdUjB1
3VIAACOt0IojrQAA3VIwdd1SAAAjrdCKI60AAN1SMHXdUgAAI63QiiOtAADdUjB13VIAACOt0Ioj
rQAA3VIwdd1SAAAjrdCKI60AAN1SMHXdUgAAI63QiiOtAADdUjB13VIAACOt0IojrQAA3VIwdd1S
AAAjrdCKI60AAN1SMHXdUgAAI63QiiOtAADdUjB13VIAACOt0IojrQAA3VIwdd1SAAAjrdCKI60A
AN1SMHXdUgAAI63QiiOtAADdUjB13VIAACOt0IojrQAA3VIwdd1SAAAjrdCKI60AAN1SMHXdUgAA
I63QiiOtAADdUjB13VIAACOt0IojrQAA3VIwdd1SAAAjrdCKI60AAN1SMHXdUgAAI63QiiOtAADd
UjB13VIAACOt0IojrQAA3VIwdd1SAAAjrdCKI60AAN1SMHXdUgAAI63QiiOtAADdUjB13VIAACOt
0IojrQAA3VIwdd1SAAAjrdCKI60AAN1SMHXdUgAAI63QiiOtAADdUjB13VIAACOt0IojrQAA3VIw
dd1SAAAjrdCKI60AAN1SMHXdUgAAI63QiiOtAADdUjB13VIAACOt0IojrQAA3VIwdd1SAAAjrdCK
I60AAN1SMHXdUgAAI63QiiOtAADdUjB13VIAACOt0IojrQAA3VIwdd1SAAAjrdCKI60AAN1SMHXd
UgAAI63QiiOtAADdUjB13VIAACOt0IojrQAA3V

Part 1.2 Qusetions:
1. Why does aliasing distortion occur in this experiment?  
   -To avoid aliasing distortion, we need to keep F<0.5×Fs, that is F less than 2kHz. When F is above the value aliasing distortion will occur.
   
2. What is the effect of aliasing on each of the six sine-waves?    
   -sound at 3.5kHz sounds pretty like that of 0.5kHz; sound at 3kHz sounds pretty like that of 1kHz; sound at 1.5kHz sounds pretty like that of 2.5kHz;
   
3. Explain what happens when F = 2000 Hz.  
   -Since F accidentlally becomes half of Fs, each sample has an amplitute of 0, so the audio if silent.

# Part 1.3-Processing a music file to demonstrate aliasing 

In [6]:
from scipy.io import wavfile 
(sampling_freq, y) = wavfile.read("SVivaldi44.1mono.wav"); 
print('original audio')
utils.Audio(y, rate=sampling_freq,) 
# rasampling without antialiasing filter
print('rasampling without antialiasing filter')
n = numpy.arange(0 , y.size/11)
y_wo = y[n*11]
utils.Audio(y_wo, rate=sampling_freq/11,)
# rasampling with resample()
print('rasampling with resample()')
from scipy.signal import resample
y_re = resample(y, (y.size)/11); 
y_re = numpy.int16(y_re)
utils.Audio(y_re, rate=sampling_freq/11,)
# rasampling with decimate()
print('rasampling with decimate()')
from scipy.signal import decimate
#need to give 'zero_phase=True' explicitly
y_de = decimate(y, 11,None,'iir',-1,True) 
y_de = numpy.int16(y_de)
utils.Audio(y_de, rate=sampling_freq/11,)

IOError: [Errno 2] No such file or directory: 'SVivaldi44.1mono.wav'

Part 1.3 Qusetions:
1. How does your program know what is the original sampling frequency?  
   -Function wavfile.read() reads it from original wav file.
   
2. Could you hear any distortion in the original wav file?  
   -No
   
3. Describe the two effects you heard with the sampling frequency reduced to about 4 kHz without antialiasing filtering.  
   -Musical notes has been lowered if they are higher in original audio; also they are out of tune .
   
4. What was the effect of the antialiasing filtering when you used 'resample' or 'decimate'?  
   -The tune of music is basically unchanged, yet it sounds more blurred.
   
5. How does the aliasing distortion affect musical notes?  
   -Musical notes are generally lowered.
   
6. Is an antialiasing filter always necessary before sampling music?  
   -Yes. We need to use a filter to wipe out sounds that has a frequency over 20kHz since they are useless to us.

# Part 1.4-Reducing the bit rate of a speech or music file by reducing the sampling frequency

In [ ]:
print('Original speech')
(Fs_spe, y_spe) = wavfile.read("HQ-speech44100-mono.wav"); 
utils.Audio(y_spe, rate=Fs_spe,)    # play original speech
y_spe_re = resample(y_spe, (y_spe.size)/10);    #resample
y_spe_re = numpy.int16(y_spe_re)
print('Down sampling of speech with factor 10')
utils.Audio(y_spe_re, rate=Fs_spe/10,)  # play resampled speech
print('Original music')
(Fs_msc, y_msc) = wavfile.read("HQ-music44100-mono.wav"); 
utils.Audio(y_msc, rate=Fs_msc,)    # play original music
y_msc_re = resample(y_msc, (y_msc.size)/3);   #resample
y_msc_re = numpy.int16(y_msc_re)
print('Down sampling of music with factor 3')
utils.Audio(y_msc_re, rate=Fs_msc/3)  # play resampled music

Part 1.4 Qusetions:
1. What is the effect on speech of reducing the sampling rate?  
   -Words become harder to recognise and volumn gets lower.
   
2. What you consider to be the minimum acceptable sampling rate for speech that you would like to hear from the built in speaker of your mobile phone?  
   -[44100/10/100]×100=4410Hz
   
3. What is the effect on music of reducing the sampling rate ?  
   -Before this, sound of violin sounds more real and sharper, after resampling it becomes more blurred.
   
4. What you consider to be the minimum acceptable sampling rate for music that you would like to hear from your mobile phone when using headphones or a good quality speaker?  
   -[44100/3/100]×100=14700Hz

# Part 1.5-Reducing the bit rate for music by reducing number of bits per sample

In [ ]:
(Fs_msc, y_msc) = wavfile.read("HQ-music44100-mono.wav"); 
print('Original form:')
utils.Audio(y_msc, rate=Fs_msc,)    # play original music
#y_cmp = numpy.round(y_msc / (2**15 - 1))  #compress music so that -1<=y_msc<=1
SM=max(abs(y_msc))           # Get maximum amplitude 
y_cmp = y_msc/float(SM)    # Scale maximum to 1
#n = input("Enter NB: ") 
#n = 16 - n 
n=9
# expansion to specified bits
#if n <8:
#    quant_y = numpy.round(y_cmp * (2**(15-n) - 1))
#else:
quant_y = numpy.round(y_cmp * (2**(15-n) - 0.5) -0.5) 
iquant_y = numpy.int16(quant_y)
# expansion to playable version
if n <8:
    iquant_y = iquant_y*(2**n)
else:
    iquant_y = (iquant_y+0.5)*(2**n)
    iquant_y = numpy.int16(iquant_y)
print('%d bits remained'%(16-n))
utils.Audio(iquant_y, rate=Fs_msc,)    # play rendered music

Part 1.5 Qusetions:
1. What do you consider to be the minimum acceptable value of NB for music sampled at 44.1 kHz?  
   -NB=7
   
2. Describe the distortion that occurs as NB is decreased from 16 towards 3.  
   -When NB>=7, no obvirous distortion occurs; From NB=6 to 3, background noises becomes louder.
   
3. Does the nature of the distortion change when the number of bits per sample becomes more or less?  
   -No, because audio rate has not changed, and there is no analysing filter.

# Part 1.6 Telephone quality speech

In [ ]:
! rm pesq_results.txt
(Fs_spe, y_spe) = wavfile.read("NarrobandSpeech8k.wav"); 
#utils.Audio(y_spe, rate=Fs_spe,)    # play original speech
#y_cmp = numpy.round(y_spe / (2**15 - 1))  #compress speech so that -1<=y_msc<=1
SM=max(abs(y_spe))           # Get maximum amplitude 
y_cmp = y_spe/float(SM)    # Scale maximum to 1

def renderspeech(n):
    quant_y = numpy.round(y_cmp * (2**(n-1) - 0.5) -0.5) # expansion to NB=n
    quant_y = (quant_y+0.5)*(2**(16-n)) # expansion to playable version
    iquant_y = numpy.int16(quant_y)
    print('rendered speech with NB=%d'%(n))
    wavfile.write("NB=%d_in_Part1-6.wav"%(n), Fs_spe, iquant_y);
    utils.audio_from_file("NB=%d_in_Part1-6.wav"%(n))  # play rendered speech from file

renderspeech(10)
renderspeech(8)
renderspeech(7)
renderspeech(6)
renderspeech(4)
renderspeech(3)

# audio comparison
from comp28512_utils import get_pesq_scores 
# compare NB=8 with reference audio
! ./linux_pesqmain +8000 NarrobandSpeech8k.wav NB=8_in_Part1-6.wav > /dev/null
pesq_results = get_pesq_scores()
score = pesq_results["NarrobandSpeech8k.wav"] ["NB=8_in_Part1-6.wav"] 
print "PESQ score for NB=8: ", score
# compare NB=6 with reference audio
! ./linux_pesqmain +8000 NarrobandSpeech8k.wav NB=6_in_Part1-6.wav > /dev/null
pesq_results = get_pesq_scores()
score = pesq_results["NarrobandSpeech8k.wav"] ["NB=6_in_Part1-6.wav"] 
print "PESQ score for NB=6: ", score
# compare NB=3 with reference audio
! ./linux_pesqmain +8000 NarrobandSpeech8k.wav NB=3_in_Part1-6.wav > /dev/null
pesq_results = get_pesq_scores()
score = pesq_results["NarrobandSpeech8k.wav"] ["NB=3_in_Part1-6.wav"] 
print "PESQ score for NB=3: ", score

Part 1.6 Qusetions:
1. Can you hear any difference between the original 16 bit per sample version and your 8 bit version?  
   -In 8 bit version there are unobvious noises that does not appear in 16 bit version.
2. Taking ‘Narrobandspeech8k.wav’ as the reference, what are the PESQ scores for (a)your 8 bit per sample version (b)a 4-bit per sample version and (c)any others you tested?  
   -NB=8:3.834;  NB=6:3.005;  NB=3:2.037
3. Compare your own assessments with the PESQ scores obtained for several values of NB.  
   -When NB is 8(and above) converted audio sounds almost the same as original version; as NB gets lower, converted audio has more blurred sound and audio samples begin to get lost at NB as low as 3. 
4. Decide what you consider to be a reasonable number of bits (NB) per sample for telephone speech when the sampling rate is 8 kHz with uniform quantisation. Summarise your reasons in one sentence, and note whether your decision is significantly different from the PESQ assessment.  
   -NB should be 8, as this is convenient for computer to store and it confines wav file size. PESQ suggests that 8-bit version is just perceptable. 
5. You have heard that land-line telephone calls use 64000 bits/second links. Based on your experiments today, do you consider that 8 bits per sample with uniform quantisation may be acceptable for telephone quality speech sampled at 8 kHz?  
   -Yes, they sound without much difference.
6. Mobile telephony cannot afford 64000 bits/second, and must use considerably less than 16,000 bits/second.  How many bits per sample would be possible using 16000 bits/second with uniform quantisation of speech sampled at 8 kHz? Based on your experiments, do you believe that reasonable quality speech can be encoded in this way for mobile telephony?   
   -2bits. No, the quality would be too low.

# Part 1.7-Log-PCM encoded speech

In [ ]:
! rm pesq_results.txt
from matplotlib import pyplot 
%matplotlib inline
rx = numpy.random.rand(200)*2-1
rx = numpy.array(sorted(rx)) # random sorted number between -1 and 1
ry = numpy.array([0]*200); ru = numpy.array([0]*200)
#apply mu-law
ry = numpy.sign(rx)*numpy.log(1+255*numpy.absolute(rx))/numpy.log(256)
fig, ax0 = pyplot.subplots(1) 
ax0.plot(rx,ry)   # plot ry against rx
ax0.grid(True)
ax0.set_title('Graph of mu-law application on data between -1 to 1')
ax0.set_xlabel("Origional data") ; ax0.set_ylabel("Data after mu-law applied") 
# apply mu-law expansion formula
ru = numpy.sign(ry)*(numpy.power(256, numpy.absolute(ry))-1)/255
fig, ax1 = pyplot.subplots(1)
ax1.plot(ry,ru)   # plot ru against ry
ax1.grid(True)
ax1.set_title('Graph of mu-law expansion application on data between -1 to 1')
ax1.set_xlabel("Data after mu-law applied") ; ax1.set_ylabel("Data after mu-law expansion applied")

#operation on audio 
(Fs_spe, x_spe) = wavfile.read("NarrobandSpeech8k.wav"); 
#utils.Audio(x_spe, rate=Fs_spe,)    # play original speech
SM=max(abs(x_spe))         # Get maximum amplitude 
x_cmp = x_spe/float(SM)    # Scale maximum to 1 (note the float) 
x_cmp = numpy.array(x_cmp)
# apply mu-law
x_mu = numpy.sign(x_cmp)*numpy.log(1+255*numpy.absolute(x_cmp))/numpy.log(256)
for n in range(3):
    # quantise to NB=8/7/6
    x_qut = numpy.round(x_mu * (2**(7-n) - 0.5) - 0.5) 
        # transmitting……
    x_qut = x_qut + 0.5
    
    # quantise to NB=16
    x_qut = numpy.round((x_qut+0.5) * (2**(8+n) - 1))
    
    SM=max(abs(x_qut))         # Get maximum amplitude 
    x_cmp = x_qut/float(SM)    # Scale maximum to 1 (note the float)
    # apply mu-law expansion formula
    x_mu_exp = numpy.sign(x_cmp)*(numpy.power(256, numpy.absolute(x_cmp))-1)/255
    
    # quantise to NB=8/7/6
    # x_qut = numpy.round(x_mu_exp * (2**(7-n) - 0.5) - 0.5)
    
    # quantise to NB=16
    # quant_y = numpy.round((x_qut+0.5) * (2**(8+n) - 1))
    quant_y = numpy.round(x_mu_exp * (2**(15) - 1))
    iquant_y = numpy.int16(quant_y)
    print('rendered speech with NB=%d quantisation'%(8-n))
    wavfile.write("NB=%d_in_Part1-7.wav"%(8-n), Fs_spe, iquant_y);
    utils.audio_from_file("NB=%d_in_Part1-7.wav"%(8-n))  # play rendered speech from file
    
# audio comparison
# compare mu-law-ed NB=8/7/6 with normal quantised NB=8/7/6 at 64kBit/s
! ./linux_pesqmain +8000 NarrobandSpeech8k.wav NB=8_in_Part1-6.wav > /dev/null
pesq_results = get_pesq_scores()
score = pesq_results["NarrobandSpeech8k.wav"] ["NB=8_in_Part1-6.wav"]
print "PESQ score for NB=8 without mu-law: ", score
! ./linux_pesqmain +8000 NarrobandSpeech8k.wav NB=8_in_Part1-7.wav > /dev/null
pesq_results = get_pesq_scores()
score = pesq_results["NarrobandSpeech8k.wav"] ["NB=8_in_Part1-7.wav"]
print "PESQ score for mu-law-ed NB=8: ", score
! ./linux_pesqmain +8000 NarrobandSpeech8k.wav NB=7_in_Part1-6.wav > /dev/null
pesq_results = get_pesq_scores()
score = pesq_results["NarrobandSpeech8k.wav"] ["NB=7_in_Part1-6.wav"]
print "PESQ score for NB=7 without mu-law: ", score
! ./linux_pesqmain +8000 NarrobandSpeech8k.wav NB=7_in_Part1-7.wav > /dev/null
pesq_results = get_pesq_scores()
score = pesq_results["NarrobandSpeech8k.wav"] ["NB=7_in_Part1-7.wav"]
print "PESQ score for mu-law-ed NB=7: ", score
! ./linux_pesqmain +8000 NarrobandSpeech8k.wav NB=6_in_Part1-6.wav > /dev/null
pesq_results = get_pesq_scores()
score = pesq_results["NarrobandSpeech8k.wav"] ["NB=6_in_Part1-6.wav"]
print "PESQ score for NB=6 without mu-law: ", score
! ./linux_pesqmain +8000 NarrobandSpeech8k.wav NB=6_in_Part1-7.wav > /dev/null
pesq_results = get_pesq_scores()
score = pesq_results["NarrobandSpeech8k.wav"] ["NB=6_in_Part1-7.wav"]
print "PESQ score for mu-law-ed NB=6: ", score

Part 1.7 Qusetions:
1. What do we learn from the mu-law companding and expansion graphs?  
   -Data valued within samples remained their value.
   
2. Compare mu-Law PCM speech at 64000 bit/s with the result of uniform quantisation at the same bit-rate.  Give PESQ scores and your own assessments for both.  
   -PESQ score- NB=8:3.834;  
      mu-law-ed NB=8:3.867.  
    In both audio I can hear conversation clearly, yet there are background noises in both files.
   
3. If you have time, compare mu-Law PCM speech with NB=7, 6, etc. with result of uniform quantisation at the same bit-rate (56,000 bit/s, 48,000 bit/s, etc).
   -PESQ score- NB=7:3.421;  
      mu-law-ed NB=7:3.42.      
    In both audio I can hear conversation clearly. Background noise get louder but still acceptable.  
   -PESQ score- NB=6:3.005;  
      mu-law-ed NB=6:2.996.      
    In both audio I can still hear conversion, yet noise gets even louder and has potential to cause disturbance.
   
4. scale to+ -1~1 -> mu-law -> uniform quantising to 8 bit -> transmission -> receive -> convert to float -> scale to -1~1 -> mu-law expansion -> quantising to 16 bit 