CC=gcc
CFLAGS=-g -std=c99 -Wall
#LDFLAGS=-lm

merge: merge
	./merge

quick: quick
	./quick

run:
		$(CC) $(CFLAGS) search.c run.c -o run

experiment:
		$(CC) $(CFLAGS) search.c experiment.c -o experiment
