CC=gcc
CFLAGS=-g -std=c99 -Wall
#LDFLAGS=-lm

part1: pangolins_part1
	./pangolins_part1

part2: pangolins_part2
	./pangolins_part2

part3: pangolins_part3
	./pangolins_part3

run:
		$(CC) $(CFLAGS) search.c run.c -o run

experiment:
		$(CC) $(CFLAGS) search.c experiment.c -o experiment
